<?php

namespace Auditix\Plugin\TemplateReport;

use App\Plugin\Capability\ProvidesReports;
use App\Plugin\Capability\ReportTemplate;
use App\Plugin\VendorPluginInterface;

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  PLUGIN TEMPLATE #5 — REPORT                                              ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 *
 * LEARNING GOAL
 * -------------
 * Provide a REPORT TEMPLATE: a document structured in typed "blocks", attached
 * to a theme. At generation time, Auditix walks the blocks and produces a PDF
 * applying the theme.
 *
 * BLOCK STRUCTURE
 * ---------------
 * Each block is an array with a `type` key. A few common types:
 *   - ['type' => 'heading', 'level' => 1..6, 'content' => 'Title']
 *   - ['type' => 'paragraph', 'content' => '<p>simple HTML</p>', 'align' => 'left']
 * There are advanced blocks (inventory tables, charts, compliance
 * recommendations, CLI commands...) — not used here to stay readable.
 *
 * THEME BINDING
 * -------------
 * `themeName` is resolved to a ReportTheme in the context. If not found, Auditix
 * falls back to the context's default theme (a report requires a theme). Here we
 * target the theme provided by the 'template-report-theme' plugin.
 *
 * On activation: a Report entity is created (managed_by_plugin), purged on
 * deactivation.
 */
final class TemplateReportPlugin implements
    VendorPluginInterface,
    ProvidesReports
{
    public function getIdentifier(): string  { return 'template-report'; }
    public function getVersion(): string      { return '1.0.0'; }
    public function getDisplayName(): string  { return 'Template — Report'; }
    public function getDescription(): string  { return 'Educational example: a block-based report template.'; }
    public function getSupportedManufacturers(): array { return []; }

    /**
     * @return ReportTemplate[]
     */
    public function provideReports(): array
    {
        return [
            new ReportTemplate(
                name: 'Template — Demonstration report',
                title: 'Demonstration report',
                subtitle: 'Generated by the template-report plugin',
                // Targets the theme from the template-report-theme plugin; otherwise default theme.
                themeName: 'Template — Teal',
                description: 'Educational report template with a few blocks.',
                locale: 'en',
                showTableOfContents: true,
                showAuthorsPage: true,
                authors: [
                    ['name' => 'Auditix', 'role' => 'Template plugin'],
                ],
                // Content: ordered list of typed blocks.
                blocks: [
                    ['type' => 'heading', 'level' => 1, 'content' => 'Introduction'],
                    ['type' => 'paragraph', 'content' => 'This report is generated by a <strong>template</strong> plugin. It illustrates the minimal structure of a document: headings and paragraphs.', 'align' => 'left'],
                    ['type' => 'heading', 'level' => 2, 'content' => 'Context'],
                    ['type' => 'paragraph', 'content' => 'Blocks are stored as JSON on the Report entity. At generation time, Auditix renders them to PDF according to the attached theme.', 'align' => 'left'],
                    ['type' => 'heading', 'level' => 2, 'content' => 'Conclusion'],
                    ['type' => 'paragraph', 'content' => 'Duplicate this plugin to ship your own pre-filled report templates.', 'align' => 'left'],
                ],
            ),
        ];
    }
}
