<?php

namespace App\Controller\Api;

use App\Entity\CollectionRule;
use App\Entity\CollectionRuleFolder;
use App\Entity\Context;
use App\Security\Voter\ContextAccessVoter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/collection-rule-folders')]
class CollectionRuleFolderController extends AbstractController
{
    #[Route('', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }
        $this->denyAccessUnlessGranted(ContextAccessVoter::ACCESS, $context);

        $name = $data['name'] ?? '';
        if (empty($name)) {
            return $this->json(['error' => 'Name is required'], Response::HTTP_BAD_REQUEST);
        }

        $parent = null;
        $parentId = $data['parentId'] ?? null;
        if ($parentId) {
            $parent = $em->getRepository(CollectionRuleFolder::class)->find($parentId);
        }

        $folder = new CollectionRuleFolder();
        $folder->setName($name);
        $folder->setType(CollectionRuleFolder::TYPE_CUSTOM);
        $folder->setParent($parent);
        $folder->setContext($context);

        $em->persist($folder);
        $em->flush();

        return $this->json([
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
            'parentId' => $parent?->getId(),
            'autoGenerated' => false,
        ], Response::HTTP_CREATED);
    }

    #[Route('/{id}', methods: ['PUT'])]
    public function update(CollectionRuleFolder $folder, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $this->denyAccessUnlessGranted(ContextAccessVoter::ACCESS, $folder);
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot rename auto-generated folders'], Response::HTTP_FORBIDDEN);
        }
        if ($folder->isManagedByPlugin()) {
            return $this->json(['error' => sprintf('Folder is managed by the "%s" plugin.', $folder->getManagedByPlugin())], Response::HTTP_FORBIDDEN);
        }

        $data = json_decode($request->getContent(), true);
        if (isset($data['name'])) {
            $folder->setName($data['name']);
        }

        $em->flush();

        return $this->json([
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
        ]);
    }

    #[Route('/{id}', methods: ['DELETE'])]
    public function delete(CollectionRuleFolder $folder, EntityManagerInterface $em): JsonResponse
    {
        $this->denyAccessUnlessGranted(ContextAccessVoter::ACCESS, $folder);
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot delete auto-generated folders'], Response::HTTP_FORBIDDEN);
        }
        if ($folder->isManagedByPlugin()) {
            return $this->json(['error' => sprintf('Folder is managed by the "%s" plugin. Disable the plugin to remove it.', $folder->getManagedByPlugin())], Response::HTTP_FORBIDDEN);
        }

        $em->remove($folder);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }

    #[Route('/{id}/toggle', methods: ['POST'])]
    public function toggle(CollectionRuleFolder $folder, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $this->denyAccessUnlessGranted(ContextAccessVoter::ACCESS, $folder);
        $data = json_decode($request->getContent(), true);
        $enabled = (bool)($data['enabled'] ?? true);

        $count = $this->applyToggleRecursive($folder, $enabled, $em);
        $em->flush();

        return $this->json(['ok' => true, 'count' => $count]);
    }

    #[Route('/{id}/clear', methods: ['POST'])]
    public function clear(CollectionRuleFolder $folder, EntityManagerInterface $em): JsonResponse
    {
        $this->denyAccessUnlessGranted(ContextAccessVoter::ACCESS, $folder);

        $count = $this->clearRecursive($folder, $em);
        $em->flush();

        return $this->json(['ok' => true, 'count' => $count]);
    }

    private function applyToggleRecursive(CollectionRuleFolder $folder, bool $enabled, EntityManagerInterface $em): int
    {
        $count = 0;
        foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $folder]) as $rule) {
            if ($rule->isEnabled() !== $enabled) {
                $rule->setEnabled($enabled);
                $count++;
            }
        }
        foreach ($em->getRepository(CollectionRuleFolder::class)->findBy(['parent' => $folder]) as $child) {
            $count += $this->applyToggleRecursive($child, $enabled, $em);
        }
        return $count;
    }

    private function clearRecursive(CollectionRuleFolder $folder, EntityManagerInterface $em): int
    {
        $count = 0;
        foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $folder]) as $rule) {
            $em->remove($rule);
            $count++;
        }
        foreach ($em->getRepository(CollectionRuleFolder::class)->findBy(['parent' => $folder]) as $child) {
            $count += $this->clearRecursive($child, $em);
            if (!$child->isAutoGenerated()) {
                $em->remove($child);
            }
        }
        return $count;
    }
}
