<?php

namespace App\Controller\Api;

use App\Entity\Collection;
use App\Entity\CollectionCommand;
use App\Entity\CollectionFolder;
use App\Entity\CollectionRule;
use App\Entity\CollectionRuleExtract;
use App\Entity\CollectionRuleFolder;
use App\Entity\InventoryCategory;
use App\Entity\Context;
use App\Entity\DeviceModel;
use App\Entity\Node;
use Doctrine\ORM\EntityManagerInterface;
use phpseclib3\Net\SSH2;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/collection-rules')]
class CollectionRuleController extends AbstractController
{
    private const SSH_TIMEOUT = 30;
    private const READ_TIMEOUT = 30;
    private const PROMPT_REGEX = '/[#>\$\]]\s*$/';
    private const STABLE_WAIT = 2;

    public function __construct(
        #[Autowire('%kernel.project_dir%')]
        private readonly string $projectDir,
    ) {}

    private function serializeRule(CollectionRule $r): array
    {
        return [
            'id' => $r->getId(),
            'name' => $r->getName(),
            'description' => $r->getDescription(),
            'enabled' => $r->isEnabled(),
            'source' => $r->getSource(),
            'command' => $r->getCommand(),
            'tag' => $r->getTag(),
            'folderId' => $r->getFolder()?->getId(),
            'extracts' => array_values(array_map(
                $this->serializeExtract(...),
                $r->getExtracts()->toArray()
            )),
            'createdAt' => $r->getCreatedAt()->format('c'),
        ];
    }

    private function serializeFolder(CollectionRuleFolder $f, EntityManagerInterface $em): array
    {
        $rules = $em->getRepository(CollectionRule::class)->findBy(
            ['folder' => $f],
            ['name' => 'ASC']
        );

        $children = $em->getRepository(CollectionRuleFolder::class)->findBy(
            ['parent' => $f],
            ['name' => 'ASC']
        );

        return [
            'id' => $f->getId(),
            'name' => $f->getName(),
            'type' => $f->getType(),
            'parentId' => $f->getParent()?->getId(),
            'manufacturerId' => $f->getManufacturer()?->getId(),
            'modelId' => $f->getModel()?->getId(),
            'autoGenerated' => $f->isAutoGenerated(),
            'children' => array_map(fn($c) => $this->serializeFolder($c, $em), $children),
            'rules' => array_map($this->serializeRule(...), $rules),
        ];
    }

    #[Route('/tree', methods: ['GET'])]
    public function tree(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        if (!$contextId) {
            return $this->json(['folders' => [], 'rootRules' => []]);
        }

        $rootFolders = $em->getRepository(CollectionRuleFolder::class)->findBy(
            ['context' => $contextId, 'parent' => null],
            ['name' => 'ASC']
        );

        $rootRules = $em->getRepository(CollectionRule::class)->findBy(
            ['context' => $contextId, 'folder' => null],
            ['name' => 'ASC']
        );

        return $this->json([
            'folders' => array_map(fn($f) => $this->serializeFolder($f, $em), $rootFolders),
            'rootRules' => array_map($this->serializeRule(...), $rootRules),
        ]);
    }

    #[Route('/by-model/{id}', methods: ['GET'])]
    public function byModel(DeviceModel $model, EntityManagerInterface $em): JsonResponse
    {
        $modelFolder = $em->getRepository(CollectionRuleFolder::class)->findOneBy([
            'model' => $model,
            'type' => CollectionRuleFolder::TYPE_MODEL,
        ]);

        $manFolder = $em->getRepository(CollectionRuleFolder::class)->findOneBy([
            'manufacturer' => $model->getManufacturer(),
            'model' => null,
            'type' => CollectionRuleFolder::TYPE_MANUFACTURER,
        ]);

        $result = [];

        $collectRecursive = function (CollectionRuleFolder $folder, bool $inherited, bool $skipModelFolders = false) use ($em, &$result, &$collectRecursive): void {
            $rules = $em->getRepository(CollectionRule::class)->findBy(['folder' => $folder], ['name' => 'ASC']);
            foreach ($rules as $r) {
                $entry = $this->serializeRule($r);
                $entry['inherited'] = $inherited;
                $entry['association'] = 'auto';
                $result[] = $entry;
            }
            $children = $em->getRepository(CollectionRuleFolder::class)->findBy(['parent' => $folder], ['name' => 'ASC']);
            foreach ($children as $child) {
                if ($skipModelFolders && $child->getType() === CollectionRuleFolder::TYPE_MODEL) continue;
                $collectRecursive($child, $inherited, $skipModelFolders);
            }
        };

        if ($manFolder) {
            $collectRecursive($manFolder, true, true);
        }
        if ($modelFolder) {
            $collectRecursive($modelFolder, false);
        }

        // Manually associated rules
        $seenIds = array_map(fn($e) => $e['id'], $result);
        foreach ($model->getManualRules() as $r) {
            if (in_array($r->getId(), $seenIds, true)) continue;
            $entry = $this->serializeRule($r);
            $entry['inherited'] = false;
            $entry['association'] = 'manual';
            $result[] = $entry;
        }

        return $this->json($result);
    }

    #[Route('/by-model/{id}/associate', methods: ['POST'])]
    public function associate(DeviceModel $model, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $ruleIds = $data['ruleIds'] ?? [];

        foreach ($ruleIds as $ruleId) {
            $rule = $em->getRepository(CollectionRule::class)->find($ruleId);
            if ($rule) {
                $model->addManualRule($rule);
            }
        }

        $em->flush();

        return $this->json(['ok' => true]);
    }

    #[Route('/by-model/{id}/dissociate', methods: ['POST'])]
    public function dissociate(DeviceModel $model, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $ruleId = $data['ruleId'] ?? null;

        if ($ruleId) {
            $rule = $em->getRepository(CollectionRule::class)->find($ruleId);
            if ($rule) {
                $model->removeManualRule($rule);
            }
        }

        $em->flush();

        return $this->json(['ok' => true]);
    }

    #[Route('/available-for-model/{id}', methods: ['GET'])]
    public function availableForModel(DeviceModel $model, EntityManagerInterface $em): JsonResponse
    {
        $context = $model->getContext();

        $excludeIds = array_map(fn($r) => $r->getId(), $model->getManualRules()->toArray());

        $modelFolder = $em->getRepository(CollectionRuleFolder::class)->findOneBy([
            'model' => $model,
            'type' => CollectionRuleFolder::TYPE_MODEL,
        ]);
        $manFolder = $em->getRepository(CollectionRuleFolder::class)->findOneBy([
            'manufacturer' => $model->getManufacturer(),
            'model' => null,
            'type' => CollectionRuleFolder::TYPE_MANUFACTURER,
        ]);

        if ($modelFolder) {
            foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $modelFolder]) as $r) {
                $excludeIds[] = $r->getId();
            }
        }
        if ($manFolder) {
            foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $manFolder]) as $r) {
                $excludeIds[] = $r->getId();
            }
        }

        // Build tree of custom folders only, with available rules
        $rootFolders = $em->getRepository(CollectionRuleFolder::class)->findBy(
            ['context' => $context, 'parent' => null, 'type' => CollectionRuleFolder::TYPE_CUSTOM],
            ['name' => 'ASC']
        );

        $folders = [];
        foreach ($rootFolders as $f) {
            $node = $this->buildAvailableRuleTree($f, $em, $excludeIds);
            if ($node) $folders[] = $node;
        }

        return $this->json(['folders' => $folders]);
    }

    private function buildAvailableRuleTree(CollectionRuleFolder $folder, EntityManagerInterface $em, array $excludeIds): ?array
    {
        $rules = [];
        foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $folder], ['name' => 'ASC']) as $r) {
            if (!in_array($r->getId(), $excludeIds, true)) {
                $rules[] = [
                    'id' => $r->getId(),
                    'name' => $r->getName(),
                    'description' => $r->getDescription(),
                    'enabled' => $r->isEnabled(),
                ];
            }
        }

        $children = [];
        foreach ($em->getRepository(CollectionRuleFolder::class)->findBy(['parent' => $folder, 'type' => CollectionRuleFolder::TYPE_CUSTOM], ['name' => 'ASC']) as $child) {
            $node = $this->buildAvailableRuleTree($child, $em, $excludeIds);
            if ($node) $children[] = $node;
        }

        if (empty($rules) && empty($children)) return null;

        return [
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
            'children' => $children,
            'rules' => $rules,
        ];
    }

    #[Route('', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $name = $data['name'] ?? '';
        if (empty($name)) {
            return $this->json(['error' => 'Name is required'], Response::HTTP_BAD_REQUEST);
        }

        $folder = null;
        $folderId = $data['folderId'] ?? null;
        if ($folderId) {
            $folder = $em->getRepository(CollectionRuleFolder::class)->find($folderId);
        }

        $rule = new CollectionRule();
        $rule->setName($name);
        $rule->setDescription($data['description'] ?? null);
        $rule->setEnabled($data['enabled'] ?? true);
        $rule->setSource($data['source'] ?? CollectionRule::SOURCE_LOCAL);
        $rule->setCommand($data['command'] ?? null);
        $rule->setTag($data['tag'] ?? null);
        $rule->setFolder($folder);
        $rule->setContext($context);

        $em->persist($rule);
        $em->flush();

        return $this->json($this->serializeRule($rule), Response::HTTP_CREATED);
    }

    #[Route('/{id}', methods: ['GET'])]
    public function show(CollectionRule $rule): JsonResponse
    {
        return $this->json($this->serializeRule($rule));
    }

    #[Route('/{id}', methods: ['PUT'])]
    public function update(CollectionRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if (isset($data['name'])) {
            $rule->setName($data['name']);
        }
        if (array_key_exists('description', $data)) {
            $rule->setDescription($data['description']);
        }
        if (isset($data['enabled'])) {
            $rule->setEnabled($data['enabled']);
        }
        if (isset($data['source'])) {
            $rule->setSource($data['source']);
        }
        if (array_key_exists('command', $data)) {
            $rule->setCommand($data['command'] ?: null);
        }
        if (array_key_exists('tag', $data)) {
            $source = $data['source'] ?? $rule->getSource();
            $rule->setTag($source === CollectionRule::SOURCE_LOCAL ? ($data['tag'] ?: null) : null);
        }
        if (array_key_exists('folderId', $data)) {
            $folder = $data['folderId'] ? $em->getRepository(CollectionRuleFolder::class)->find($data['folderId']) : null;
            $rule->setFolder($folder);
        }

        $em->flush();

        return $this->json($this->serializeRule($rule));
    }

    #[Route('/{id}/test', methods: ['POST'])]
    public function test(CollectionRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $nodeId = $data['nodeId'] ?? null;

        if (!$nodeId) {
            return $this->json(['error' => 'nodeId is required'], Response::HTTP_BAD_REQUEST);
        }

        $node = $em->getRepository(Node::class)->find($nodeId);
        if (!$node) {
            return $this->json(['error' => 'Node not found'], Response::HTTP_NOT_FOUND);
        }

        $command = $rule->getCommand();
        if (!$command) {
            return $this->json(['error' => 'No command configured on this rule'], Response::HTTP_BAD_REQUEST);
        }

        if ($rule->getSource() === CollectionRule::SOURCE_LOCAL) {
            return $this->testLocal($rule, $node, $em);
        }

        return $this->testSSH($rule, $node, $em);
    }

    private function testLocal(CollectionRule $rule, Node $node, EntityManagerInterface $em): JsonResponse
    {
        $command = $rule->getCommand();
        $tag = $rule->getTag();
        $commandSlug = $this->slugify($command);

        // Find the latest collection for this node, optionally filtered by tag
        $conn = $em->getConnection();
        $sql = 'SELECT id FROM collection WHERE node_id = :node AND status = :status';
        $params = ['node' => $node->getId(), 'status' => Collection::STATUS_COMPLETED];

        if ($tag) {
            $sql .= ' AND tags::text LIKE :tag';
            $params['tag'] = '%"' . $tag . '"%';
        }

        $sql .= ' ORDER BY completed_at DESC LIMIT 1';
        $row = $conn->fetchAssociative($sql, $params);
        $collection = $row ? $em->getRepository(Collection::class)->find($row['id']) : null;
        if (!$collection) {
            return $this->json([
                'success' => false,
                'error' => $tag
                    ? 'No completed collection found for this node with tag "' . $tag . '"'
                    : 'No completed collection found for this node',
            ]);
        }

        $baseDir = $this->projectDir . '/var/' . $collection->getStoragePath();

        // Search for a file matching the command slug in any command subdirectory
        $foundContent = null;
        if (is_dir($baseDir)) {
            $dirs = scandir($baseDir);
            foreach ($dirs as $dir) {
                if ($dir === '.' || $dir === '..') continue;
                $filePath = $baseDir . '/' . $dir . '/' . $commandSlug . '.txt';
                if (file_exists($filePath)) {
                    $foundContent = file_get_contents($filePath);
                    break;
                }
            }
        }

        if ($foundContent === null) {
            return $this->json([
                'success' => false,
                'error' => 'No collected file found for command "' . $command . '" in collection #' . $collection->getId(),
            ]);
        }

        return $this->json([
            'success' => true,
            'output' => $foundContent,
            'collectionId' => $collection->getId(),
            'source' => 'local',
        ]);
    }

    private function testSSH(CollectionRule $rule, Node $node, EntityManagerInterface $em): JsonResponse
    {
        $profile = $node->getProfile();
        $cliCred = $profile?->getCliCredential();

        if (!$cliCred || !$cliCred->getUsername()) {
            return $this->json([
                'success' => false,
                'error' => 'No CLI credentials configured on this node\'s profile',
            ]);
        }

        $ip = $node->getIpAddress();
        $port = $cliCred->getPort() ?: 22;
        $model = $node->getModel();
        $command = $rule->getCommand();

        try {
            $ssh = new SSH2($ip, $port, self::SSH_TIMEOUT);
            $ssh->enablePTY();

            if (!$ssh->login($cliCred->getUsername(), $cliCred->getPassword() ?? '')) {
                return $this->json([
                    'success' => false,
                    'error' => 'SSH authentication failed for ' . $cliCred->getUsername() . '@' . $ip . ':' . $port,
                ]);
            }

            $ssh->setTimeout(self::READ_TIMEOUT);

            // Read initial prompt/banner
            $this->readFullResponse($ssh);

            // Execute connection script
            $connectionScript = $model?->getConnectionScript();
            if ($connectionScript) {
                $scriptLines = array_filter(array_map('trim', explode("\n", $connectionScript)), fn($l) => $l !== '');
                foreach ($scriptLines as $line) {
                    $ssh->write($line . "\n");
                    $this->readFullResponse($ssh);
                }
            }

            // Execute the command
            $ssh->write($command . "\n");
            $response = $this->readFullResponse($ssh);

            // Clean up response: remove echoed command and trailing prompt
            $responseLines = explode("\n", $response);
            if (!empty($responseLines) && str_contains($responseLines[0], trim($command))) {
                array_shift($responseLines);
            }
            if (!empty($responseLines) && preg_match(self::PROMPT_REGEX, end($responseLines))) {
                array_pop($responseLines);
            }

            $ssh->disconnect();

            return $this->json([
                'success' => true,
                'output' => implode("\n", $responseLines),
                'source' => 'ssh',
            ]);

        } catch (\Throwable $e) {
            return $this->json([
                'success' => false,
                'error' => 'SSH error: ' . $e->getMessage(),
            ]);
        }
    }

    private function readFullResponse(SSH2 $ssh): string
    {
        $output = $ssh->read(self::PROMPT_REGEX, SSH2::READ_REGEX);

        $ssh->setTimeout(self::STABLE_WAIT);

        while (true) {
            $extra = @$ssh->read(self::PROMPT_REGEX, SSH2::READ_REGEX);
            if ($extra === false || $extra === '') {
                break;
            }
            $output .= $extra;
        }

        $ssh->setTimeout(self::READ_TIMEOUT);

        return $output;
    }

    private function slugify(string $text): string
    {
        $text = preg_replace('/[^a-z0-9]+/i', '-', $text);
        return strtolower(trim($text, '-'));
    }

    private function serializeExtract(CollectionRuleExtract $e): array
    {
        return [
            'id' => $e->getId(),
            'name' => $e->getName(),
            'regex' => $e->getRegex(),
            'multiline' => $e->isMultiline(),
            'keyMode' => $e->getKeyMode(),
            'keyManual' => $e->getKeyManual(),
            'keyExtractId' => $e->getKeyExtract()?->getId(),
            'keyGroup' => $e->getKeyGroup(),
            'keyLabel' => $e->getKeyLabel(),
            'valueGroup' => $e->getValueGroup(),
            'valueMap' => $e->getValueMap(),
            'categoryId' => $e->getCategory()?->getId(),
            'categoryName' => $e->getCategory()?->getName(),
            'categoryKeyLabel' => $e->getCategory()?->getKeyLabel(),
            'nodeField' => $e->getNodeField(),
            'nodeFieldGroup' => $e->getNodeFieldGroup(),
            'position' => $e->getPosition(),
        ];
    }

    #[Route('/{id}/extracts', methods: ['GET'])]
    public function listExtracts(CollectionRule $rule): JsonResponse
    {
        return $this->json(array_values(array_map(
            $this->serializeExtract(...),
            $rule->getExtracts()->toArray()
        )));
    }

    #[Route('/{id}/extracts', methods: ['POST'])]
    public function createExtract(CollectionRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $name = $data['name'] ?? '';
        $regex = $data['regex'] ?? '';

        if (empty($name) || empty($regex)) {
            return $this->json(['error' => 'Name and regex are required'], Response::HTTP_BAD_REQUEST);
        }

        // Set position to end
        $maxPos = 0;
        foreach ($rule->getExtracts() as $e) {
            if ($e->getPosition() > $maxPos) $maxPos = $e->getPosition();
        }

        $extract = new CollectionRuleExtract();
        $extract->setName($name);
        $extract->setRegex($regex);
        $extract->setMultiline($data['multiline'] ?? false);
        $extract->setKeyMode($data['keyMode'] ?? CollectionRuleExtract::KEY_MODE_MANUAL);
        $extract->setKeyManual($data['keyManual'] ?? null);

        $extract->setKeyGroup(isset($data['keyGroup']) ? (int)$data['keyGroup'] : null);
        $extract->setKeyLabel($data['keyLabel'] ?? null);
        $extract->setValueGroup(isset($data['valueGroup']) ? (int)$data['valueGroup'] : null);
        $extract->setValueMap($data['valueMap'] ?? null);

        if (!empty($data['keyExtractId'])) {
            $keyExt = $em->getRepository(CollectionRuleExtract::class)->find($data['keyExtractId']);
            $extract->setKeyExtract($keyExt);
        }
        if (!empty($data['categoryId'])) {
            $cat = $em->getRepository(InventoryCategory::class)->find($data['categoryId']);
            $extract->setCategory($cat);
        }
        $extract->setNodeField($data['nodeField'] ?? null);
        $extract->setNodeFieldGroup(isset($data['nodeFieldGroup']) ? (int)$data['nodeFieldGroup'] : null);

        $extract->setPosition($maxPos + 1);
        $rule->addExtract($extract);

        $em->flush();

        return $this->json($this->serializeExtract($extract), Response::HTTP_CREATED);
    }

    #[Route('/{ruleId}/extracts/{extractId}', methods: ['PUT'])]
    public function updateExtract(int $ruleId, int $extractId, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $extract = $em->getRepository(CollectionRuleExtract::class)->find($extractId);
        if (!$extract || $extract->getRule()->getId() !== $ruleId) {
            return $this->json(['error' => 'Extract not found'], Response::HTTP_NOT_FOUND);
        }

        $data = json_decode($request->getContent(), true);
        if (isset($data['name'])) {
            $extract->setName($data['name']);
        }
        if (isset($data['regex'])) {
            $extract->setRegex($data['regex']);
        }
        if (isset($data['multiline'])) {
            $extract->setMultiline($data['multiline']);
        }
        if (isset($data['keyMode'])) {
            $extract->setKeyMode($data['keyMode']);
        }
        if (array_key_exists('keyManual', $data)) {
            $extract->setKeyManual($data['keyManual'] ?: null);
        }
        if (array_key_exists('keyGroup', $data)) {
            $extract->setKeyGroup($data['keyGroup'] !== null ? (int)$data['keyGroup'] : null);
        }
        if (array_key_exists('keyLabel', $data)) {
            $extract->setKeyLabel($data['keyLabel'] ?: null);
        }
        if (array_key_exists('valueGroup', $data)) {
            $extract->setValueGroup($data['valueGroup'] !== null ? (int)$data['valueGroup'] : null);
        }
        if (array_key_exists('valueMap', $data)) {
            $extract->setValueMap($data['valueMap']);
        }
        if (array_key_exists('keyExtractId', $data)) {
            $keyExt = $data['keyExtractId'] ? $em->getRepository(CollectionRuleExtract::class)->find($data['keyExtractId']) : null;
            $extract->setKeyExtract($keyExt);
        }
        if (array_key_exists('categoryId', $data)) {
            $cat = $data['categoryId'] ? $em->getRepository(InventoryCategory::class)->find($data['categoryId']) : null;
            $extract->setCategory($cat);
        }
        if (array_key_exists('nodeField', $data)) {
            $extract->setNodeField($data['nodeField'] ?: null);
        }
        if (array_key_exists('nodeFieldGroup', $data)) {
            $extract->setNodeFieldGroup($data['nodeFieldGroup'] !== null ? (int)$data['nodeFieldGroup'] : null);
        }

        $em->flush();

        return $this->json($this->serializeExtract($extract));
    }

    #[Route('/{id}/extracts/reorder', methods: ['POST'])]
    public function reorderExtracts(CollectionRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $ids = $data['ids'] ?? [];

        $extractsById = [];
        foreach ($rule->getExtracts() as $e) {
            $extractsById[$e->getId()] = $e;
        }

        foreach ($ids as $pos => $id) {
            if (isset($extractsById[$id])) {
                $extractsById[$id]->setPosition($pos);
            }
        }

        $em->flush();

        return $this->json(array_values(array_map(
            $this->serializeExtract(...),
            $rule->getExtracts()->toArray()
        )));
    }

    #[Route('/{ruleId}/extracts/{extractId}', methods: ['DELETE'])]
    public function deleteExtract(int $ruleId, int $extractId, EntityManagerInterface $em): JsonResponse
    {
        $extract = $em->getRepository(CollectionRuleExtract::class)->find($extractId);
        if (!$extract || $extract->getRule()->getId() !== $ruleId) {
            return $this->json(['error' => 'Extract not found'], Response::HTTP_NOT_FOUND);
        }

        $em->remove($extract);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }

    #[Route('/{id}', methods: ['DELETE'])]
    public function delete(CollectionRule $rule, EntityManagerInterface $em): JsonResponse
    {
        $em->remove($rule);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }
}
