<?php

namespace App\Controller\Api;

use App\Entity\CollectionCommand;
use App\Entity\CollectionFolder;
use App\Entity\Context;
use App\Entity\DeviceModel;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/collection-commands')]
class CollectionCommandController extends AbstractController
{
    private function serializeCommand(CollectionCommand $c): array
    {
        return [
            'id' => $c->getId(),
            'name' => $c->getName(),
            'description' => $c->getDescription(),
            'commands' => $c->getCommands(),
            'enabled' => $c->isEnabled(),
            'folderId' => $c->getFolder()?->getId(),
            'createdAt' => $c->getCreatedAt()->format('c'),
        ];
    }

    private function serializeFolder(CollectionFolder $f, EntityManagerInterface $em): array
    {
        $commands = $em->getRepository(CollectionCommand::class)->findBy(
            ['folder' => $f],
            ['name' => 'ASC']
        );

        $children = $em->getRepository(CollectionFolder::class)->findBy(
            ['parent' => $f],
            ['name' => 'ASC']
        );

        return [
            'id' => $f->getId(),
            'name' => $f->getName(),
            'type' => $f->getType(),
            'parentId' => $f->getParent()?->getId(),
            'manufacturerId' => $f->getManufacturer()?->getId(),
            'modelId' => $f->getModel()?->getId(),
            'autoGenerated' => $f->isAutoGenerated(),
            'children' => array_map(fn($c) => $this->serializeFolder($c, $em), $children),
            'commands' => array_map($this->serializeCommand(...), $commands),
        ];
    }

    #[Route('/tree', methods: ['GET'])]
    public function tree(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        if (!$contextId) {
            return $this->json(['folders' => [], 'rootCommands' => []]);
        }

        // Root folders (no parent)
        $rootFolders = $em->getRepository(CollectionFolder::class)->findBy(
            ['context' => $contextId, 'parent' => null],
            ['name' => 'ASC']
        );

        // Root commands (no folder)
        $rootCommands = $em->getRepository(CollectionCommand::class)->findBy(
            ['context' => $contextId, 'folder' => null],
            ['name' => 'ASC']
        );

        return $this->json([
            'folders' => array_map(fn($f) => $this->serializeFolder($f, $em), $rootFolders),
            'rootCommands' => array_map($this->serializeCommand(...), $rootCommands),
        ]);
    }

    #[Route('/by-model/{id}', methods: ['GET'])]
    public function byModel(DeviceModel $model, EntityManagerInterface $em): JsonResponse
    {
        // Find the model's folder and manufacturer's folder
        $modelFolder = $em->getRepository(CollectionFolder::class)->findOneBy([
            'model' => $model,
            'type' => CollectionFolder::TYPE_MODEL,
        ]);

        $manFolder = $em->getRepository(CollectionFolder::class)->findOneBy([
            'manufacturer' => $model->getManufacturer(),
            'model' => null,
            'type' => CollectionFolder::TYPE_MANUFACTURER,
        ]);

        $result = [];

        // Commands in manufacturer folder (inherited)
        if ($manFolder) {
            $inherited = $em->getRepository(CollectionCommand::class)->findBy(
                ['folder' => $manFolder],
                ['name' => 'ASC']
            );
            foreach ($inherited as $c) {
                $entry = $this->serializeCommand($c);
                $entry['inherited'] = true;
                $entry['association'] = 'auto';
                $result[] = $entry;
            }
        }

        // Commands in model folder (direct)
        if ($modelFolder) {
            $direct = $em->getRepository(CollectionCommand::class)->findBy(
                ['folder' => $modelFolder],
                ['name' => 'ASC']
            );
            foreach ($direct as $c) {
                $entry = $this->serializeCommand($c);
                $entry['inherited'] = false;
                $entry['association'] = 'auto';
                $result[] = $entry;
            }
        }

        // Manually associated commands
        $seenIds = array_map(fn($e) => $e['id'], $result);
        foreach ($model->getManualCommands() as $c) {
            if (in_array($c->getId(), $seenIds, true)) continue;
            $entry = $this->serializeCommand($c);
            $entry['inherited'] = false;
            $entry['association'] = 'manual';
            $result[] = $entry;
        }

        return $this->json($result);
    }

    #[Route('/by-model/{id}/associate', methods: ['POST'])]
    public function associate(DeviceModel $model, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $commandIds = $data['commandIds'] ?? [];

        foreach ($commandIds as $cmdId) {
            $cmd = $em->getRepository(CollectionCommand::class)->find($cmdId);
            if ($cmd) {
                $model->addManualCommand($cmd);
            }
        }

        $em->flush();

        return $this->json(['ok' => true]);
    }

    #[Route('/by-model/{id}/dissociate', methods: ['POST'])]
    public function dissociate(DeviceModel $model, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $commandId = $data['commandId'] ?? null;

        if ($commandId) {
            $cmd = $em->getRepository(CollectionCommand::class)->find($commandId);
            if ($cmd) {
                $model->removeManualCommand($cmd);
            }
        }

        $em->flush();

        return $this->json(['ok' => true]);
    }

    #[Route('/available-for-model/{id}', methods: ['GET'])]
    public function availableForModel(DeviceModel $model, EntityManagerInterface $em): JsonResponse
    {
        $context = $model->getContext();

        // IDs already associated (auto or manual)
        $excludeIds = array_map(fn($c) => $c->getId(), $model->getManualCommands()->toArray());

        $modelFolder = $em->getRepository(CollectionFolder::class)->findOneBy([
            'model' => $model,
            'type' => CollectionFolder::TYPE_MODEL,
        ]);
        $manFolder = $em->getRepository(CollectionFolder::class)->findOneBy([
            'manufacturer' => $model->getManufacturer(),
            'model' => null,
            'type' => CollectionFolder::TYPE_MANUFACTURER,
        ]);

        if ($modelFolder) {
            foreach ($em->getRepository(CollectionCommand::class)->findBy(['folder' => $modelFolder]) as $c) {
                $excludeIds[] = $c->getId();
            }
        }
        if ($manFolder) {
            foreach ($em->getRepository(CollectionCommand::class)->findBy(['folder' => $manFolder]) as $c) {
                $excludeIds[] = $c->getId();
            }
        }

        // Build tree of custom folders only, with available commands
        $rootFolders = $em->getRepository(CollectionFolder::class)->findBy(
            ['context' => $context, 'parent' => null, 'type' => CollectionFolder::TYPE_CUSTOM],
            ['name' => 'ASC']
        );

        $folders = [];
        foreach ($rootFolders as $f) {
            $node = $this->buildAvailableCmdTree($f, $em, $excludeIds);
            if ($node) $folders[] = $node;
        }

        return $this->json(['folders' => $folders]);
    }

    private function buildAvailableCmdTree(CollectionFolder $folder, EntityManagerInterface $em, array $excludeIds): ?array
    {
        $commands = [];
        foreach ($em->getRepository(CollectionCommand::class)->findBy(['folder' => $folder], ['name' => 'ASC']) as $c) {
            if (!in_array($c->getId(), $excludeIds, true)) {
                $commands[] = $this->serializeCommand($c);
            }
        }

        $children = [];
        foreach ($em->getRepository(CollectionFolder::class)->findBy(['parent' => $folder, 'type' => CollectionFolder::TYPE_CUSTOM], ['name' => 'ASC']) as $child) {
            $node = $this->buildAvailableCmdTree($child, $em, $excludeIds);
            if ($node) $children[] = $node;
        }

        if (empty($commands) && empty($children)) return null;

        return [
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
            'children' => $children,
            'commands' => $commands,
        ];
    }

    #[Route('', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $name = $data['name'] ?? '';
        if (empty($name)) {
            return $this->json(['error' => 'Name is required'], Response::HTTP_BAD_REQUEST);
        }

        $commands = $data['commands'] ?? '';
        if (empty($commands)) {
            return $this->json(['error' => 'Commands are required'], Response::HTTP_BAD_REQUEST);
        }

        $folder = null;
        $folderId = $data['folderId'] ?? null;
        if ($folderId) {
            $folder = $em->getRepository(CollectionFolder::class)->find($folderId);
        }

        $cmd = new CollectionCommand();
        $cmd->setName($name);
        $cmd->setDescription($data['description'] ?? null);
        $cmd->setCommands($commands);
        $cmd->setEnabled($data['enabled'] ?? true);
        $cmd->setFolder($folder);
        $cmd->setContext($context);

        $em->persist($cmd);
        $em->flush();

        return $this->json($this->serializeCommand($cmd), Response::HTTP_CREATED);
    }

    #[Route('/{id}', methods: ['PUT'])]
    public function update(CollectionCommand $cmd, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if (isset($data['name'])) {
            $cmd->setName($data['name']);
        }
        if (array_key_exists('description', $data)) {
            $cmd->setDescription($data['description']);
        }
        if (isset($data['commands'])) {
            $cmd->setCommands($data['commands']);
        }
        if (isset($data['enabled'])) {
            $cmd->setEnabled($data['enabled']);
        }
        if (array_key_exists('folderId', $data)) {
            $folder = $data['folderId'] ? $em->getRepository(CollectionFolder::class)->find($data['folderId']) : null;
            $cmd->setFolder($folder);
        }

        $em->flush();

        return $this->json($this->serializeCommand($cmd));
    }

    #[Route('/{id}', methods: ['DELETE'])]
    public function delete(CollectionCommand $cmd, EntityManagerInterface $em): JsonResponse
    {
        $em->remove($cmd);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }
}
