<?php

namespace App\Controller\Api;

use App\Entity\CollectionFolder;
use App\Entity\Context;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/collection-folders')]
class CollectionFolderController extends AbstractController
{
    #[Route('', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $name = $data['name'] ?? '';
        if (empty($name)) {
            return $this->json(['error' => 'Name is required'], Response::HTTP_BAD_REQUEST);
        }

        $parent = null;
        $parentId = $data['parentId'] ?? null;
        if ($parentId) {
            $parent = $em->getRepository(CollectionFolder::class)->find($parentId);
        }

        $folder = new CollectionFolder();
        $folder->setName($name);
        $folder->setType(CollectionFolder::TYPE_CUSTOM);
        $folder->setParent($parent);
        $folder->setContext($context);

        $em->persist($folder);
        $em->flush();

        return $this->json([
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
            'parentId' => $parent?->getId(),
            'autoGenerated' => false,
        ], Response::HTTP_CREATED);
    }

    #[Route('/{id}', methods: ['PUT'])]
    public function update(CollectionFolder $folder, Request $request, EntityManagerInterface $em): JsonResponse
    {
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot rename auto-generated folders'], Response::HTTP_FORBIDDEN);
        }

        $data = json_decode($request->getContent(), true);
        if (isset($data['name'])) {
            $folder->setName($data['name']);
        }

        $em->flush();

        return $this->json([
            'id' => $folder->getId(),
            'name' => $folder->getName(),
            'type' => $folder->getType(),
        ]);
    }

    #[Route('/{id}', methods: ['DELETE'])]
    public function delete(CollectionFolder $folder, EntityManagerInterface $em): JsonResponse
    {
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot delete auto-generated folders'], Response::HTTP_FORBIDDEN);
        }

        $em->remove($folder);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }
}
