<?php

namespace App\Controller\Api;

use App\Entity\CompliancePolicy;
use App\Entity\ComplianceRule;
use App\Entity\ComplianceRuleFolder;
use App\Entity\Context;
use App\Entity\Node;
use App\Service\ComplianceEvaluator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/compliance-rules')]
class ComplianceRuleController extends AbstractController
{
    public function __construct(
        private readonly ComplianceEvaluator $evaluator,
    ) {}

    private function serializeRule(ComplianceRule $r): array
    {
        return [
            'id' => $r->getId(),
            'identifier' => $r->getIdentifier(),
            'name' => $r->getName(),
            'description' => $r->getDescription(),
            'enabled' => $r->isEnabled(),
            'dataSources' => $r->getDataSources(),
            'conditionTree' => $r->getConditionTree(),
            'multiRowMessages' => $r->getMultiRowMessages(),
            'folderId' => $r->getFolder()?->getId(),
            'createdAt' => $r->getCreatedAt()->format('c'),
        ];
    }

    private function serializeFolder(ComplianceRuleFolder $f, EntityManagerInterface $em): array
    {
        $rules = $em->getRepository(ComplianceRule::class)->findBy(
            ['folder' => $f],
            ['identifier' => 'ASC', 'name' => 'ASC']
        );

        $children = $em->getRepository(ComplianceRuleFolder::class)->findBy(
            ['parent' => $f],
            ['name' => 'ASC']
        );

        return [
            'id' => $f->getId(),
            'name' => $f->getName(),
            'parentId' => $f->getParent()?->getId(),
            'policyId' => $f->getPolicy()?->getId(),
            'autoGenerated' => $f->isAutoGenerated(),
            'children' => array_map(fn($c) => $this->serializeFolder($c, $em), $children),
            'rules' => array_map($this->serializeRule(...), $rules),
        ];
    }

    #[Route('/tree', methods: ['GET'])]
    public function tree(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        if (!$contextId) {
            return $this->json(['folders' => [], 'rootRules' => []]);
        }

        $context = $em->getRepository(Context::class)->find($contextId);
        if (!$context) {
            return $this->json(['folders' => [], 'rootRules' => []]);
        }

        $policies = $em->getRepository(CompliancePolicy::class)->findBy(
            ['context' => $context],
            ['name' => 'ASC']
        );

        foreach ($policies as $policy) {
            $existing = $em->getRepository(ComplianceRuleFolder::class)->findOneBy([
                'policy' => $policy,
                'parent' => null,
            ]);
            if (!$existing) {
                $folder = new ComplianceRuleFolder();
                $folder->setName($policy->getName());
                $folder->setPolicy($policy);
                $folder->setContext($context);
                $em->persist($folder);
            } else {
                if ($existing->getName() !== $policy->getName()) {
                    $existing->setName($policy->getName());
                }
            }
        }
        $em->flush();

        $policyFolders = $em->getRepository(ComplianceRuleFolder::class)->findBy([
            'context' => $context,
            'parent' => null,
        ]);
        foreach ($policyFolders as $pf) {
            if ($pf->getPolicy() !== null) {
                $found = false;
                foreach ($policies as $p) {
                    if ($p->getId() === $pf->getPolicy()->getId()) {
                        $found = true;
                        break;
                    }
                }
                if (!$found) {
                    $em->remove($pf);
                }
            }
        }
        $em->flush();

        $rootFolders = $em->getRepository(ComplianceRuleFolder::class)->findBy(
            ['context' => $contextId, 'parent' => null],
            ['name' => 'ASC']
        );

        $rootRules = $em->getRepository(ComplianceRule::class)->findBy(
            ['context' => $contextId, 'folder' => null],
            ['identifier' => 'ASC', 'name' => 'ASC']
        );

        return $this->json([
            'folders' => array_map(fn($f) => $this->serializeFolder($f, $em), $rootFolders),
            'rootRules' => array_map($this->serializeRule(...), $rootRules),
        ]);
    }

    #[Route('', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $contextId = $request->query->get('context');

        if (empty($data['name'])) {
            return $this->json(['error' => 'Name is required'], Response::HTTP_BAD_REQUEST);
        }

        $context = $em->getRepository(Context::class)->find($contextId);
        if (!$context) {
            return $this->json(['error' => 'Context not found'], Response::HTTP_NOT_FOUND);
        }

        $rule = new ComplianceRule();
        $rule->setName($data['name']);
        $rule->setContext($context);

        if (array_key_exists('identifier', $data)) {
            $rule->setIdentifier($data['identifier'] ?: null);
        }
        if (array_key_exists('description', $data)) {
            $rule->setDescription($data['description']);
        }
        if (array_key_exists('enabled', $data)) {
            $rule->setEnabled((bool) $data['enabled']);
        }

        $folderId = $data['folderId'] ?? null;
        if ($folderId) {
            $folder = $em->getRepository(ComplianceRuleFolder::class)->find($folderId);
            $rule->setFolder($folder);
        }

        $this->applySourceFields($rule, $data, $em);

        $em->persist($rule);
        $em->flush();

        return $this->json($this->serializeRule($rule), Response::HTTP_CREATED);
    }

    #[Route('/{id}', methods: ['GET'])]
    public function show(ComplianceRule $rule): JsonResponse
    {
        return $this->json($this->serializeRule($rule));
    }

    #[Route('/{id}', methods: ['PUT'])]
    public function update(ComplianceRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if (isset($data['name'])) {
            $rule->setName($data['name']);
        }
        if (array_key_exists('identifier', $data)) {
            $rule->setIdentifier($data['identifier'] ?: null);
        }
        if (array_key_exists('description', $data)) {
            $rule->setDescription($data['description']);
        }
        if (array_key_exists('enabled', $data)) {
            $rule->setEnabled((bool) $data['enabled']);
        }
        if (array_key_exists('folderId', $data)) {
            $folder = $data['folderId'] ? $em->getRepository(ComplianceRuleFolder::class)->find($data['folderId']) : null;
            $rule->setFolder($folder);
        }

        $this->applySourceFields($rule, $data, $em);

        $em->flush();

        return $this->json($this->serializeRule($rule));
    }

    #[Route('/{id}', methods: ['DELETE'])]
    public function delete(ComplianceRule $rule, EntityManagerInterface $em): JsonResponse
    {
        $em->remove($rule);
        $em->flush();

        return $this->json(null, Response::HTTP_NO_CONTENT);
    }

    #[Route('/{id}/test', methods: ['POST'])]
    public function test(ComplianceRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $nodeId = $data['nodeId'] ?? null;

        if (!$nodeId) {
            return $this->json(['error' => 'nodeId is required'], Response::HTTP_BAD_REQUEST);
        }

        $node = $em->getRepository(Node::class)->find($nodeId);
        if (!$node) {
            return $this->json(['error' => 'Node not found'], Response::HTTP_NOT_FOUND);
        }

        $sources = $rule->getDataSources();
        if (empty($sources)) {
            return $this->json([
                'success' => true,
                'node' => ['id' => $node->getId(), 'name' => $node->getName() ?? $node->getIpAddress()],
                'sources' => [],
                'message' => 'No data sources configured',
            ]);
        }

        $fields = $this->evaluator->getAllSourceFields($rule, $node);
        if (isset($fields['_error'])) {
            return $this->json(['success' => false, 'error' => $fields['_error']]);
        }

        return $this->json([
            'success' => true,
            'node' => ['id' => $node->getId(), 'name' => $node->getName() ?? $node->getHostname() ?? $node->getIpAddress()],
            'fields' => $fields,
        ]);
    }

    #[Route('/{id}/evaluate', methods: ['POST'])]
    public function evaluate(ComplianceRule $rule, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $nodeId = $data['nodeId'] ?? null;

        if (!$nodeId) {
            return $this->json(['error' => 'nodeId is required'], Response::HTTP_BAD_REQUEST);
        }

        $node = $em->getRepository(Node::class)->find($nodeId);
        if (!$node) {
            return $this->json(['error' => 'Node not found'], Response::HTTP_NOT_FOUND);
        }

        $result = $this->evaluator->evaluateRule($rule, $node);

        return $this->json([
            'success' => true,
            'node' => [
                'id' => $node->getId(),
                'name' => $node->getName() ?? $node->getHostname() ?? $node->getIpAddress(),
                'ipAddress' => $node->getIpAddress(),
            ],
            'evaluation' => $result,
        ]);
    }

    // Source data fetching and evaluation logic is now in ComplianceEvaluator service

    private function applySourceFields(ComplianceRule $rule, array $data, EntityManagerInterface $em): void
    {
        if (array_key_exists('dataSources', $data)) {
            $rule->setDataSources(is_array($data['dataSources']) ? $data['dataSources'] : []);
        }
        if (array_key_exists('conditionTree', $data)) {
            $tree = $data['conditionTree'];
            if ($tree !== null) {
                $this->validateConditionTree($tree);
            }
            $rule->setConditionTree($tree);
        }
        if (array_key_exists('multiRowMessages', $data)) {
            $rule->setMultiRowMessages($data['multiRowMessages']);
        }
    }

    private function validateConditionTree(array $tree): void
    {
        if (!isset($tree['blocks']) || !is_array($tree['blocks'])) {
            throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('conditionTree must have a blocks array');
        }
        $this->validateBlocks($tree['blocks']);
    }

    private function validateBlocks(array $blocks): void
    {
        $validOperators = ['equals', 'not_equals', 'exists', 'not_exists', 'contains', 'not_contains', 'matches', 'greater_than', 'less_than', 'is_empty', 'is_not_empty'];
        $validStatuses = ['compliant', 'non_compliant', 'error', 'not_applicable'];
        $validSeverities = ['info', 'low', 'medium', 'high', 'critical'];

        foreach ($blocks as $i => $block) {
            $type = $block['type'] ?? null;
            if ($i === 0 && $type !== 'if') {
                throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('First block must be "if"');
            }
            if ($i > 0 && !in_array($type, ['else_if', 'else'])) {
                throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Subsequent blocks must be "else_if" or "else"');
            }

            foreach (($block['conditions'] ?? []) as $cond) {
                if (!in_array($cond['operator'] ?? '', $validOperators)) {
                    throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid operator: ' . ($cond['operator'] ?? ''));
                }
            }

            $children = $block['children'] ?? [];
            $result = $block['result'] ?? null;

            if (!empty($children)) {
                $this->validateBlocks($children);
            }

            if ($result !== null) {
                if (!in_array($result['status'] ?? '', $validStatuses)) {
                    throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Invalid result status');
                }
                if (($result['status'] ?? '') === 'non_compliant' && !in_array($result['severity'] ?? '', $validSeverities)) {
                    throw new \Symfony\Component\HttpKernel\Exception\BadRequestHttpException('Non-compliant results require a valid severity');
                }
            }
        }
    }

}
