<?php

namespace App\Controller\Api;

use App\Entity\CollectionCommand;
use App\Entity\CollectionFolder;
use App\Entity\CollectionRule;
use App\Entity\CollectionRuleExtract;
use App\Entity\CollectionRuleFolder;
use App\Entity\ComplianceRule;
use App\Entity\ComplianceRuleFolder;
use App\Entity\Context;
use App\Entity\InventoryCategory;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class FolderExportController extends AbstractController
{
    // ═══════════════════════════════════════════════════════════════════
    //  COLLECTION COMMAND FOLDERS
    // ═══════════════════════════════════════════════════════════════════

    #[Route('/api/collection-folders/{id}/export', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function exportCommandFolder(CollectionFolder $folder, EntityManagerInterface $em): Response
    {
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot export auto-generated folders'], Response::HTTP_FORBIDDEN);
        }

        $cmdRefIndex = 0;
        $data = [
            '_format' => 'auditix-command-folder-export',
            '_version' => 1,
            '_exportedAt' => (new \DateTimeImmutable())->format('c'),
            'folder' => $this->serializeCmdFolderTree($folder, $em, $cmdRefIndex),
        ];

        $safeName = preg_replace('/[^a-zA-Z0-9_\-.]/', '_', $folder->getName());
        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        return new Response($json, Response::HTTP_OK, [
            'Content-Type' => 'application/json',
            'Content-Disposition' => sprintf('attachment; filename="commands-%s.json"', $safeName),
        ]);
    }

    #[Route('/api/collection-folders/preview-import', methods: ['POST'], priority: 10)]
    public function previewImportCommandFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $data = $this->parseImportFile($request, 'auditix-command-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $folder = $data['folder'];
        $commandCount = $this->countCmdFolderCommands($folder);
        $subfolderCount = $this->countSubfolders($folder);

        return $this->json([
            'folderName' => $folder['name'],
            'commandCount' => $commandCount,
            'subfolderCount' => $subfolderCount,
        ]);
    }

    #[Route('/api/collection-folders/import', methods: ['POST'], priority: 10)]
    public function importCommandFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $parentId = $request->query->getInt('parentId') ?: null;
        $parent = $parentId ? $em->getRepository(CollectionFolder::class)->find($parentId) : null;

        $data = $this->parseImportFile($request, 'auditix-command-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $em->beginTransaction();
        try {
            $this->importCmdFolderTree($data['folder'], $parent, $context, $em);
            $em->flush();
            $em->commit();
            return $this->json(['success' => true], Response::HTTP_CREATED);
        } catch (\Throwable $e) {
            $em->rollback();
            return $this->json(['error' => 'Import failed: ' . $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  COLLECTION RULE FOLDERS
    // ═══════════════════════════════════════════════════════════════════

    #[Route('/api/collection-rule-folders/{id}/export', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function exportRuleFolder(CollectionRuleFolder $folder, EntityManagerInterface $em): Response
    {
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot export auto-generated folders'], Response::HTTP_FORBIDDEN);
        }

        $ruleRefIndex = 0;
        $extractRefIndex = 0;
        $extractRefMap = [];
        $data = [
            '_format' => 'auditix-rule-folder-export',
            '_version' => 1,
            '_exportedAt' => (new \DateTimeImmutable())->format('c'),
            'folder' => $this->serializeRuleFolderTree($folder, $em, $ruleRefIndex, $extractRefIndex, $extractRefMap),
        ];

        // Resolve keyExtractRef
        $this->resolveExtractRefsInFolder($data['folder'], $extractRefMap);

        $safeName = preg_replace('/[^a-zA-Z0-9_\-.]/', '_', $folder->getName());
        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        return new Response($json, Response::HTTP_OK, [
            'Content-Type' => 'application/json',
            'Content-Disposition' => sprintf('attachment; filename="rules-%s.json"', $safeName),
        ]);
    }

    #[Route('/api/collection-rule-folders/preview-import', methods: ['POST'], priority: 10)]
    public function previewImportRuleFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $data = $this->parseImportFile($request, 'auditix-rule-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $folder = $data['folder'];
        [$ruleCount, $extractCount] = $this->countRuleFolderItems($folder);
        $subfolderCount = $this->countSubfolders($folder);

        $categoryNames = [];
        $this->collectRuleFolderCategories($folder, $categoryNames);
        $categoryNames = array_unique($categoryNames);

        $categoriesPreview = [];
        foreach ($categoryNames as $catName) {
            $existing = $em->getRepository(InventoryCategory::class)->findOneBy([
                'name' => $catName,
                'context' => $context,
            ]);
            $categoriesPreview[] = ['name' => $catName, 'exists' => $existing !== null];
        }

        return $this->json([
            'folderName' => $folder['name'],
            'ruleCount' => $ruleCount,
            'extractCount' => $extractCount,
            'subfolderCount' => $subfolderCount,
            'categories' => $categoriesPreview,
        ]);
    }

    #[Route('/api/collection-rule-folders/import', methods: ['POST'], priority: 10)]
    public function importRuleFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $parentId = $request->query->getInt('parentId') ?: null;
        $parent = $parentId ? $em->getRepository(CollectionRuleFolder::class)->find($parentId) : null;

        $data = $this->parseImportFile($request, 'auditix-rule-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $em->beginTransaction();
        try {
            $extractRefMap = [];
            $pendingKeyExtracts = [];
            $this->importRuleFolderTree($data['folder'], $parent, $context, $em, $extractRefMap, $pendingKeyExtracts);

            foreach ($pendingKeyExtracts as [$extract, $keyExtractRef]) {
                if (isset($extractRefMap[$keyExtractRef])) {
                    $extract->setKeyExtract($extractRefMap[$keyExtractRef]);
                }
            }

            $em->flush();
            $em->commit();
            return $this->json(['success' => true], Response::HTTP_CREATED);
        } catch (\Throwable $e) {
            $em->rollback();
            return $this->json(['error' => 'Import failed: ' . $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  HELPERS
    // ═══════════════════════════════════════════════════════════════════

    private function parseImportFile(Request $request, string $expectedFormat): array|JsonResponse
    {
        $file = $request->files->get('file');
        if (!$file) {
            return $this->json(['error' => 'File is required'], Response::HTTP_BAD_REQUEST);
        }
        $data = json_decode(file_get_contents($file->getPathname()), true);
        if (!$data || ($data['_format'] ?? null) !== $expectedFormat) {
            return $this->json(['error' => 'Invalid export file format'], Response::HTTP_BAD_REQUEST);
        }
        return $data;
    }

    // ── Command folder serialization ──

    private function serializeCmdFolderTree(CollectionFolder $folder, EntityManagerInterface $em, int &$cmdRefIndex): array
    {
        $commands = [];
        foreach ($em->getRepository(CollectionCommand::class)->findBy(['folder' => $folder]) as $cmd) {
            $commands[] = [
                '_ref' => 'cmd:' . $cmdRefIndex++,
                'name' => $cmd->getName(),
                'description' => $cmd->getDescription(),
                'commands' => $cmd->getCommands(),
                'enabled' => $cmd->isEnabled(),
            ];
        }

        $children = [];
        foreach ($folder->getChildren() as $child) {
            if ($child->getType() !== CollectionFolder::TYPE_CUSTOM) continue;
            $children[] = $this->serializeCmdFolderTree($child, $em, $cmdRefIndex);
        }

        return [
            'name' => $folder->getName(),
            'commands' => $commands,
            'children' => $children,
        ];
    }

    private function importCmdFolderTree(array $data, ?CollectionFolder $parent, Context $context, EntityManagerInterface $em): void
    {
        $folder = new CollectionFolder();
        $folder->setName($data['name']);
        $folder->setType(CollectionFolder::TYPE_CUSTOM);
        $folder->setParent($parent);
        $folder->setContext($context);
        $em->persist($folder);

        foreach ($data['commands'] ?? [] as $cmdData) {
            $cmd = new CollectionCommand();
            $cmd->setName($cmdData['name']);
            $cmd->setDescription($cmdData['description'] ?? null);
            $cmd->setCommands($cmdData['commands']);
            $cmd->setEnabled($cmdData['enabled'] ?? true);
            $cmd->setFolder($folder);
            $cmd->setContext($context);
            $em->persist($cmd);
        }

        foreach ($data['children'] ?? [] as $childData) {
            $this->importCmdFolderTree($childData, $folder, $context, $em);
        }
    }

    private function countCmdFolderCommands(array $folder): int
    {
        $count = count($folder['commands'] ?? []);
        foreach ($folder['children'] ?? [] as $child) {
            $count += $this->countCmdFolderCommands($child);
        }
        return $count;
    }

    // ── Rule folder serialization ──

    private function serializeRuleFolderTree(CollectionRuleFolder $folder, EntityManagerInterface $em, int &$ruleRefIndex, int &$extractRefIndex, array &$extractRefMap): array
    {
        $rules = [];
        foreach ($em->getRepository(CollectionRule::class)->findBy(['folder' => $folder]) as $rule) {
            $ruleRef = 'rule:' . $ruleRefIndex++;
            $extracts = [];
            foreach ($rule->getExtracts() as $extract) {
                $eRef = 'extract:' . $extractRefIndex++;
                $extractRefMap[$extract->getId()] = $eRef;
                $extracts[] = [
                    '_ref' => $eRef,
                    'name' => $extract->getName(),
                    'regex' => $extract->getRegex(),
                    'multiline' => $extract->isMultiline(),
                    'keyMode' => $extract->getKeyMode(),
                    'keyManual' => $extract->getKeyManual(),
                    '_keyExtractId' => $extract->getKeyExtract()?->getId(),
                    'keyGroup' => $extract->getKeyGroup(),
                    'keyLabel' => $extract->getKeyLabel(),
                    'valueGroup' => $extract->getValueGroup(),
                    'valueMap' => $extract->getValueMap(),
                    'categoryName' => $extract->getCategory()?->getName(),
                    'categoryKeyLabel' => $extract->getCategory()?->getKeyLabel(),
                    'nodeField' => $extract->getNodeField(),
                    'nodeFieldGroup' => $extract->getNodeFieldGroup(),
                    'position' => $extract->getPosition(),
                ];
            }
            $rules[] = [
                '_ref' => $ruleRef,
                'name' => $rule->getName(),
                'description' => $rule->getDescription(),
                'enabled' => $rule->isEnabled(),
                'source' => $rule->getSource(),
                'command' => $rule->getCommand(),
                'tag' => $rule->getTag(),
                'extracts' => $extracts,
            ];
        }

        $children = [];
        foreach ($folder->getChildren() as $child) {
            if ($child->getType() !== CollectionRuleFolder::TYPE_CUSTOM) continue;
            $children[] = $this->serializeRuleFolderTree($child, $em, $ruleRefIndex, $extractRefIndex, $extractRefMap);
        }

        return [
            'name' => $folder->getName(),
            'rules' => $rules,
            'children' => $children,
        ];
    }

    private function resolveExtractRefsInFolder(array &$folder, array $extractRefMap): void
    {
        foreach ($folder['rules'] as &$rule) {
            foreach ($rule['extracts'] as &$extract) {
                $keyExtractId = $extract['_keyExtractId'];
                unset($extract['_keyExtractId']);
                $extract['keyExtractRef'] = $keyExtractId !== null ? ($extractRefMap[$keyExtractId] ?? null) : null;
            }
        }
        foreach ($folder['children'] as &$child) {
            $this->resolveExtractRefsInFolder($child, $extractRefMap);
        }
    }

    private function importRuleFolderTree(array $data, ?CollectionRuleFolder $parent, Context $context, EntityManagerInterface $em, array &$extractRefMap, array &$pendingKeyExtracts): void
    {
        $folder = new CollectionRuleFolder();
        $folder->setName($data['name']);
        $folder->setType(CollectionRuleFolder::TYPE_CUSTOM);
        $folder->setParent($parent);
        $folder->setContext($context);
        $em->persist($folder);

        foreach ($data['rules'] ?? [] as $ruleData) {
            $rule = new CollectionRule();
            $rule->setName($ruleData['name']);
            $rule->setDescription($ruleData['description'] ?? null);
            $rule->setEnabled($ruleData['enabled'] ?? true);
            $rule->setSource($ruleData['source'] ?? CollectionRule::SOURCE_LOCAL);
            $rule->setCommand($ruleData['command'] ?? null);
            $rule->setTag($ruleData['tag'] ?? null);
            $rule->setFolder($folder);
            $rule->setContext($context);
            $em->persist($rule);

            foreach ($ruleData['extracts'] ?? [] as $extData) {
                $extract = new CollectionRuleExtract();
                $extract->setName($extData['name']);
                $extract->setRegex($extData['regex']);
                $extract->setMultiline($extData['multiline'] ?? false);
                $extract->setKeyMode($extData['keyMode'] ?? CollectionRuleExtract::KEY_MODE_MANUAL);
                $extract->setKeyManual($extData['keyManual'] ?? null);
                $extract->setKeyGroup($extData['keyGroup'] ?? null);
                $extract->setKeyLabel($extData['keyLabel'] ?? null);
                $extract->setValueGroup($extData['valueGroup'] ?? null);
                $extract->setValueMap($extData['valueMap'] ?? null);
                $extract->setNodeField($extData['nodeField'] ?? null);
                $extract->setNodeFieldGroup($extData['nodeFieldGroup'] ?? null);
                $extract->setPosition($extData['position'] ?? 0);
                $extract->setRule($rule);

                if (!empty($extData['categoryName'])) {
                    $category = $em->getRepository(InventoryCategory::class)->findOneBy([
                        'name' => $extData['categoryName'],
                        'context' => $context,
                    ]);
                    if (!$category) {
                        $category = new InventoryCategory();
                        $category->setName($extData['categoryName']);
                        $category->setKeyLabel($extData['categoryKeyLabel'] ?? null);
                        $category->setContext($context);
                        $em->persist($category);
                    }
                    $extract->setCategory($category);
                }

                $em->persist($extract);
                $extractRefMap[$extData['_ref']] = $extract;

                if (!empty($extData['keyExtractRef'])) {
                    $pendingKeyExtracts[] = [$extract, $extData['keyExtractRef']];
                }
            }
        }

        foreach ($data['children'] ?? [] as $childData) {
            $this->importRuleFolderTree($childData, $folder, $context, $em, $extractRefMap, $pendingKeyExtracts);
        }
    }

    private function countRuleFolderItems(array $folder): array
    {
        $ruleCount = count($folder['rules'] ?? []);
        $extractCount = 0;
        foreach ($folder['rules'] ?? [] as $rule) {
            $extractCount += count($rule['extracts'] ?? []);
        }
        foreach ($folder['children'] ?? [] as $child) {
            [$rc, $ec] = $this->countRuleFolderItems($child);
            $ruleCount += $rc;
            $extractCount += $ec;
        }
        return [$ruleCount, $extractCount];
    }

    private function countSubfolders(array $folder): int
    {
        $count = count($folder['children'] ?? []);
        foreach ($folder['children'] ?? [] as $child) {
            $count += $this->countSubfolders($child);
        }
        return $count;
    }

    private function collectRuleFolderCategories(array $folder, array &$names): void
    {
        foreach ($folder['rules'] ?? [] as $rule) {
            foreach ($rule['extracts'] ?? [] as $extract) {
                if (!empty($extract['categoryName'])) {
                    $names[] = $extract['categoryName'];
                }
            }
        }
        foreach ($folder['children'] ?? [] as $child) {
            $this->collectRuleFolderCategories($child, $names);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  COMPLIANCE RULE FOLDERS
    // ═══════════════════════════════════════════════════════════════════

    #[Route('/api/compliance-rule-folders/{id}/export', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function exportComplianceRuleFolder(ComplianceRuleFolder $folder, EntityManagerInterface $em): Response
    {
        if ($folder->isAutoGenerated()) {
            return $this->json(['error' => 'Cannot export auto-generated folders'], Response::HTTP_FORBIDDEN);
        }

        $ruleRefIndex = 0;
        $data = [
            '_format' => 'auditix-compliance-rule-folder-export',
            '_version' => 1,
            '_exportedAt' => (new \DateTimeImmutable())->format('c'),
            'folder' => $this->serializeComplianceRuleFolderTree($folder, $em, $ruleRefIndex),
        ];

        $safeName = preg_replace('/[^a-zA-Z0-9_\-.]/', '_', $folder->getName());
        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        return new Response($json, Response::HTTP_OK, [
            'Content-Type' => 'application/json',
            'Content-Disposition' => sprintf('attachment; filename="compliance-rules-%s.json"', $safeName),
        ]);
    }

    #[Route('/api/compliance-rule-folders/preview-import', methods: ['POST'], priority: 10)]
    public function previewImportComplianceRuleFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $data = $this->parseImportFile($request, 'auditix-compliance-rule-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $folder = $data['folder'];
        $ruleCount = $this->countComplianceRuleFolderItems($folder);
        $subfolderCount = $this->countSubfolders($folder);

        $categoryNames = [];
        $this->collectComplianceRuleFolderCategories($folder, $categoryNames);
        $categoryNames = array_unique($categoryNames);

        $categoriesPreview = [];
        foreach ($categoryNames as $catName) {
            $existing = $em->getRepository(InventoryCategory::class)->findOneBy([
                'name' => $catName,
                'context' => $context,
            ]);
            $categoriesPreview[] = ['name' => $catName, 'exists' => $existing !== null];
        }

        return $this->json([
            'folderName' => $folder['name'],
            'ruleCount' => $ruleCount,
            'subfolderCount' => $subfolderCount,
            'categories' => $categoriesPreview,
        ]);
    }

    #[Route('/api/compliance-rule-folders/import', methods: ['POST'], priority: 10)]
    public function importComplianceRuleFolder(Request $request, EntityManagerInterface $em): JsonResponse
    {
        $contextId = $request->query->getInt('context');
        $context = $contextId ? $em->getRepository(Context::class)->find($contextId) : null;
        if (!$context) {
            return $this->json(['error' => 'Context is required'], Response::HTTP_BAD_REQUEST);
        }

        $parentId = $request->query->getInt('parentId') ?: null;
        $parent = $parentId ? $em->getRepository(ComplianceRuleFolder::class)->find($parentId) : null;

        $data = $this->parseImportFile($request, 'auditix-compliance-rule-folder-export');
        if ($data instanceof JsonResponse) return $data;

        $em->beginTransaction();
        try {
            $this->importComplianceRuleFolderTree($data['folder'], $parent, $context, $em);
            $em->flush();
            $em->commit();
            return $this->json(['success' => true], Response::HTTP_CREATED);
        } catch (\Throwable $e) {
            $em->rollback();
            return $this->json(['error' => 'Import failed: ' . $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    // ── Compliance rule folder helpers ──

    private function serializeComplianceRuleFolderTree(ComplianceRuleFolder $folder, EntityManagerInterface $em, int &$ruleRefIndex): array
    {
        $rules = [];
        foreach ($em->getRepository(ComplianceRule::class)->findBy(['folder' => $folder], ['identifier' => 'ASC', 'name' => 'ASC']) as $rule) {
            $rules[] = $this->serializeComplianceRule($rule, 'rule:' . $ruleRefIndex++);
        }

        $children = [];
        foreach ($em->getRepository(ComplianceRuleFolder::class)->findBy(['parent' => $folder], ['name' => 'ASC']) as $child) {
            $children[] = $this->serializeComplianceRuleFolderTree($child, $em, $ruleRefIndex);
        }

        return [
            'name' => $folder->getName(),
            'rules' => $rules,
            'children' => $children,
        ];
    }

    private function serializeComplianceRule(ComplianceRule $rule, string $ref): array
    {
        return [
            '_ref' => $ref,
            'identifier' => $rule->getIdentifier(),
            'name' => $rule->getName(),
            'description' => $rule->getDescription(),
            'enabled' => $rule->isEnabled(),
            'sourceType' => $rule->getSourceType(),
            'sourceCategoryName' => $rule->getSourceCategory()?->getName(),
            'sourceKey' => $rule->getSourceKey(),
            'sourceValue' => $rule->getSourceValue(),
            'sourceCommand' => $rule->getSourceCommand(),
            'sourceTag' => $rule->getSourceTag(),
            'sourceRegex' => $rule->getSourceRegex(),
            'sourceResultMode' => $rule->getSourceResultMode(),
            'sourceValueMap' => $rule->getSourceValueMap(),
            'sourceKeyGroup' => $rule->getSourceKeyGroup(),
            'conditionTree' => $rule->getConditionTree(),
            'multiRowMessages' => $rule->getMultiRowMessages(),
        ];
    }

    private function importComplianceRuleFolderTree(array $data, ?ComplianceRuleFolder $parent, Context $context, EntityManagerInterface $em): void
    {
        $folder = new ComplianceRuleFolder();
        $folder->setName($data['name']);
        $folder->setParent($parent);
        $folder->setContext($context);
        $em->persist($folder);

        foreach ($data['rules'] ?? [] as $ruleData) {
            $this->createComplianceRule($ruleData, $folder, $context, $em);
        }

        foreach ($data['children'] ?? [] as $childData) {
            $this->importComplianceRuleFolderTree($childData, $folder, $context, $em);
        }
    }

    private function createComplianceRule(array $data, ComplianceRuleFolder $folder, Context $context, EntityManagerInterface $em): ComplianceRule
    {
        $rule = new ComplianceRule();
        $rule->setIdentifier($data['identifier'] ?? null);
        $rule->setName($data['name']);
        $rule->setDescription($data['description'] ?? null);
        $rule->setEnabled($data['enabled'] ?? true);
        $rule->setSourceType($data['sourceType'] ?? ComplianceRule::SOURCE_NONE);
        $rule->setSourceKey($data['sourceKey'] ?? null);
        $rule->setSourceValue($data['sourceValue'] ?? null);
        $rule->setSourceCommand($data['sourceCommand'] ?? null);
        $rule->setSourceTag($data['sourceTag'] ?? null);
        $rule->setSourceRegex($data['sourceRegex'] ?? null);
        $rule->setSourceResultMode($data['sourceResultMode'] ?? null);
        $rule->setSourceValueMap($data['sourceValueMap'] ?? null);
        $rule->setSourceKeyGroup($data['sourceKeyGroup'] ?? null);
        $rule->setConditionTree($data['conditionTree'] ?? null);
        $rule->setMultiRowMessages($data['multiRowMessages'] ?? null);
        $rule->setFolder($folder);
        $rule->setContext($context);

        if (!empty($data['sourceCategoryName'])) {
            $category = $em->getRepository(InventoryCategory::class)->findOneBy([
                'name' => $data['sourceCategoryName'],
                'context' => $context,
            ]);
            if (!$category) {
                $category = new InventoryCategory();
                $category->setName($data['sourceCategoryName']);
                $category->setContext($context);
                $em->persist($category);
            }
            $rule->setSourceCategory($category);
        }

        $em->persist($rule);
        return $rule;
    }

    private function countComplianceRuleFolderItems(array $folder): int
    {
        $count = count($folder['rules'] ?? []);
        foreach ($folder['children'] ?? [] as $child) {
            $count += $this->countComplianceRuleFolderItems($child);
        }
        return $count;
    }

    private function collectComplianceRuleFolderCategories(array $folder, array &$names): void
    {
        foreach ($folder['rules'] ?? [] as $rule) {
            if (!empty($rule['sourceCategoryName'])) {
                $names[] = $rule['sourceCategoryName'];
            }
        }
        foreach ($folder['children'] ?? [] as $child) {
            $this->collectComplianceRuleFolderCategories($child, $names);
        }
    }
}
