<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Per-key compliance evaluation: store the per-inventory-key detail of a rule
 * evaluated in loop mode (one row per interface), and aggregate counters on the
 * parent result for proportional scoring.
 */
final class Version20260625100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add compliance_result_item and per-key counters on compliance_result';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE compliance_result ADD per_key BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE compliance_result ADD items_total INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE compliance_result ADD items_non_compliant INT NOT NULL DEFAULT 0');

        $this->addSql('CREATE TABLE compliance_result_item (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            result_id INT NOT NULL,
            item_key VARCHAR(255) NOT NULL,
            status VARCHAR(20) NOT NULL,
            severity VARCHAR(10) DEFAULT NULL,
            message TEXT DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_result_item_result ON compliance_result_item (result_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_result_item_key ON compliance_result_item (result_id, item_key)');
        $this->addSql('ALTER TABLE compliance_result_item ADD CONSTRAINT FK_result_item_result FOREIGN KEY (result_id) REFERENCES compliance_result (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE compliance_result_item DROP CONSTRAINT FK_result_item_result');
        $this->addSql('DROP TABLE compliance_result_item');
        $this->addSql('ALTER TABLE compliance_result DROP per_key');
        $this->addSql('ALTER TABLE compliance_result DROP items_total');
        $this->addSql('ALTER TABLE compliance_result DROP items_non_compliant');
    }
}
