<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add report_word_version table to keep the history of generated Word (.docx)
 * exports, with one row per generation (per node for node reports).
 */
final class Version20260624100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add report_word_version table for Word export versioning';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report_word_version (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            report_id INT NOT NULL,
            node_id INT DEFAULT NULL,
            node_label VARCHAR(255) DEFAULT NULL,
            version_number INT NOT NULL,
            file_path VARCHAR(500) DEFAULT NULL,
            file_size INT DEFAULT NULL,
            status VARCHAR(20) DEFAULT NULL,
            error TEXT DEFAULT NULL,
            is_current BOOLEAN NOT NULL DEFAULT FALSE,
            created_by VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX idx_report_word_version_report ON report_word_version (report_id)');
        $this->addSql('CREATE INDEX idx_report_word_version_node ON report_word_version (node_id)');
        $this->addSql('ALTER TABLE report_word_version ADD CONSTRAINT FK_report_word_version_report FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_word_version ADD CONSTRAINT FK_report_word_version_node FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE report_word_version DROP CONSTRAINT FK_report_word_version_report');
        $this->addSql('ALTER TABLE report_word_version DROP CONSTRAINT FK_report_word_version_node');
        $this->addSql('DROP TABLE report_word_version');
    }
}
