<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add topology folders (tree organisation of schemas) and link Topology to a folder.
 */
final class Version20260618195606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add topology_folder table and topology.folder_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE topology_folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, context_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_topology_folder_context ON topology_folder (context_id)');
        $this->addSql('CREATE INDEX idx_topology_folder_parent ON topology_folder (parent_id)');
        $this->addSql('ALTER TABLE topology_folder ADD CONSTRAINT FK_184A04EE727ACA70 FOREIGN KEY (parent_id) REFERENCES topology_folder (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topology_folder ADD CONSTRAINT FK_184A04EE6B00C1CF FOREIGN KEY (context_id) REFERENCES context (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topology ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE topology ADD CONSTRAINT FK_1198610C162CB942 FOREIGN KEY (folder_id) REFERENCES topology_folder (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1198610C162CB942 ON topology (folder_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE topology DROP CONSTRAINT FK_1198610C162CB942');
        $this->addSql('DROP INDEX IDX_1198610C162CB942');
        $this->addSql('ALTER TABLE topology DROP folder_id');
        $this->addSql('ALTER TABLE topology_folder DROP CONSTRAINT FK_184A04EE727ACA70');
        $this->addSql('ALTER TABLE topology_folder DROP CONSTRAINT FK_184A04EE6B00C1CF');
        $this->addSql('DROP TABLE topology_folder');
    }
}
