<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add report schema folders (tree organisation) and link ReportSchema to a folder.
 */
final class Version20260618200554 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add report_schema_folder table and report_schema.folder_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report_schema_folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, context_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_report_schema_folder_context ON report_schema_folder (context_id)');
        $this->addSql('CREATE INDEX idx_report_schema_folder_parent ON report_schema_folder (parent_id)');
        $this->addSql('ALTER TABLE report_schema_folder ADD CONSTRAINT FK_3A12E6EF727ACA70 FOREIGN KEY (parent_id) REFERENCES report_schema_folder (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_schema_folder ADD CONSTRAINT FK_3A12E6EF6B00C1CF FOREIGN KEY (context_id) REFERENCES context (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_schema ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE report_schema ADD CONSTRAINT FK_917D94CD162CB942 FOREIGN KEY (folder_id) REFERENCES report_schema_folder (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_917D94CD162CB942 ON report_schema (folder_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE report_schema DROP CONSTRAINT FK_917D94CD162CB942');
        $this->addSql('DROP INDEX IDX_917D94CD162CB942');
        $this->addSql('ALTER TABLE report_schema DROP folder_id');
        $this->addSql('ALTER TABLE report_schema_folder DROP CONSTRAINT FK_3A12E6EF727ACA70');
        $this->addSql('ALTER TABLE report_schema_folder DROP CONSTRAINT FK_3A12E6EF6B00C1CF');
        $this->addSql('DROP TABLE report_schema_folder');
    }
}
