"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/I18nProvider";
import { useAppContext } from "@/components/ContextProvider";
import {
  Loader2,
  FileSearch,
  FolderOpen,
  FolderClosed,
  FolderPlus,
  FileText,
  Plus,
  Pencil,
  Trash2,
  X,
  ChevronRight,
  ChevronDown,
  ToggleLeft,
  ToggleRight,
  Monitor,
  Wifi,
} from "lucide-react";

interface Rule {
  id: number;
  name: string;
  description: string | null;
  enabled: boolean;
  source: "local" | "ssh";
  command: string | null;
  tag: string | null;
  folderId: number | null;
  extracts: unknown[];
  createdAt: string;
}

interface Folder {
  id: number;
  name: string;
  type: "custom" | "manufacturer" | "model";
  parentId: number | null;
  autoGenerated: boolean;
  children: Folder[];
  rules: Rule[];
}

interface TreeData {
  folders: Folder[];
  rootRules: Rule[];
}

export default function CollectionRulesPage() {
  const { t } = useI18n();
  const { current } = useAppContext();
  const router = useRouter();
  const [tree, setTree] = useState<TreeData>({ folders: [], rootRules: [] });
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  // Rule modal
  const [ruleModal, setRuleModal] = useState(false);
  const [editingRule, setEditingRule] = useState<Rule | null>(null);
  const [ruleFolderId, setRuleFolderId] = useState<number | null>(null);
  const [ruleName, setRuleName] = useState("");
  const [ruleDesc, setRuleDesc] = useState("");
  const [ruleEnabled, setRuleEnabled] = useState(true);
  const [saving, setSaving] = useState(false);

  // Folder modal
  const [folderModal, setFolderModal] = useState(false);
  const [editingFolder, setEditingFolder] = useState<Folder | null>(null);
  const [folderParentId, setFolderParentId] = useState<number | null>(null);
  const [folderName, setFolderName] = useState("");

  // Delete confirm
  const [deleteConfirm, setDeleteConfirm] = useState<{ type: "rule" | "folder"; id: number } | null>(null);

  const load = useCallback(async () => {
    if (!current) return;
    const res = await fetch(`/api/collection-rules/tree?context=${current.id}`);
    if (res.ok) setTree(await res.json());
    setLoading(false);
  }, [current]);

  useEffect(() => { load(); }, [load]);

  const toggle = (id: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  // Rule CRUD
  const openCreateRule = (folderId: number | null) => {
    setEditingRule(null);
    setRuleFolderId(folderId);
    setRuleName("");
    setRuleDesc("");
    setRuleEnabled(true);
    setRuleModal(true);
  };

  const openEditRule = (rule: Rule) => {
    router.push(`/collection-rules/${rule.id}`);
  };

  const saveRule = async () => {
    if (!ruleName.trim()) return;
    setSaving(true);
    try {
      const body = { name: ruleName, description: ruleDesc || null, enabled: ruleEnabled, folderId: ruleFolderId };
      if (editingRule) {
        await fetch(`/api/collection-rules/${editingRule.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      } else {
        await fetch(`/api/collection-rules?context=${current!.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      }
      setRuleModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const toggleRule = async (rule: Rule) => {
    await fetch(`/api/collection-rules/${rule.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !rule.enabled }) });
    await load();
  };

  const deleteRule = async (id: number) => {
    await fetch(`/api/collection-rules/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  // Folder CRUD
  const openCreateFolder = (parentId: number | null) => {
    setEditingFolder(null);
    setFolderParentId(parentId);
    setFolderName("");
    setFolderModal(true);
  };

  const openEditFolder = (folder: Folder) => {
    setEditingFolder(folder);
    setFolderParentId(folder.parentId);
    setFolderName(folder.name);
    setFolderModal(true);
  };

  const saveFolder = async () => {
    if (!folderName.trim()) return;
    setSaving(true);
    try {
      if (editingFolder) {
        await fetch(`/api/collection-rule-folders/${editingFolder.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName }) });
      } else {
        await fetch(`/api/collection-rule-folders?context=${current!.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName, parentId: folderParentId }) });
      }
      setFolderModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const deleteFolder = async (id: number) => {
    await fetch(`/api/collection-rule-folders/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  if (loading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-slate-900 dark:text-white" /></div>;
  }

  const isEmpty = tree.folders.length === 0 && tree.rootRules.length === 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">{t("collection_rules.title")}</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{t("collection_rules.subtitle")}</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => openCreateFolder(null)} className="flex items-center gap-2 rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
            <FolderPlus className="h-4 w-4" />
            {t("collection_rules.newFolder")}
          </button>
          <button onClick={() => openCreateRule(null)} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-4 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 transition-colors">
            <Plus className="h-4 w-4" />
            {t("collection_rules.newRule")}
          </button>
        </div>
      </div>

      {isEmpty ? (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-12 text-center shadow-sm">
          <FileSearch className="mx-auto h-8 w-8 text-slate-300 dark:text-slate-600 mb-2" />
          <p className="text-sm text-slate-400 dark:text-slate-500">{t("collection_rules.noRules")}</p>
        </div>
      ) : (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm overflow-hidden">
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {tree.folders.map((folder) => (
              <RuleFolderNode key={`folder-${folder.id}`} folder={folder} depth={0} t={t}
                expanded={expanded} toggle={toggle}
                openCreateRule={openCreateRule} openEditRule={openEditRule} toggleRule={toggleRule}
                openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
                deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
                deleteRule={deleteRule} deleteFolder={deleteFolder}
              />
            ))}
            {tree.rootRules.map((rule) => (
              <RuleRow key={`rule-${rule.id}`} rule={rule} depth={0} t={t}
                onEdit={() => openEditRule(rule)} onToggle={() => toggleRule(rule)}
                deleteConfirm={deleteConfirm?.type === "rule" && deleteConfirm.id === rule.id}
                onDelete={() => setDeleteConfirm({ type: "rule", id: rule.id })}
                onDeleteConfirm={() => deleteRule(rule.id)}
                onDeleteCancel={() => setDeleteConfirm(null)}
              />
            ))}
          </div>
        </div>
      )}

      {/* Rule Modal */}
      {ruleModal && (
        <Modal title={t("collection_rules.newRule")} onClose={() => setRuleModal(false)}>
          <div className="space-y-4">
            <Field label={t("collection_rules.name")}>
              <input type="text" value={ruleName} onChange={(e) => setRuleName(e.target.value)} placeholder={t("collection_rules.namePlaceholder")} className={inputCls} />
            </Field>
            <Field label={t("collection_rules.description")}>
              <input type="text" value={ruleDesc} onChange={(e) => setRuleDesc(e.target.value)} placeholder={t("collection_rules.descriptionPlaceholder")} className={inputCls} />
            </Field>
            <label className="flex items-center gap-3 cursor-pointer">
              <button type="button" onClick={() => setRuleEnabled(!ruleEnabled)}>
                {ruleEnabled ? <ToggleRight className="h-6 w-6 text-emerald-500" /> : <ToggleLeft className="h-6 w-6 text-slate-400" />}
              </button>
              <span className="text-sm text-slate-700 dark:text-slate-300">{t("collection_rules.enabled")}</span>
            </label>
          </div>
          <ModalFooter t={t} saving={saving} disabled={!ruleName.trim()} onCancel={() => setRuleModal(false)} onSave={saveRule} />
        </Modal>
      )}

      {/* Folder Modal */}
      {folderModal && (
        <Modal title={editingFolder ? t("collection_rules.editFolder") : t("collection_rules.newFolder")} onClose={() => setFolderModal(false)}>
          <Field label={t("collection_rules.folderName")}>
            <input type="text" value={folderName} onChange={(e) => setFolderName(e.target.value)} placeholder={t("collection_rules.folderNamePlaceholder")} className={inputCls} />
          </Field>
          <ModalFooter t={t} saving={saving} disabled={!folderName.trim()} onCancel={() => setFolderModal(false)} onSave={saveFolder} />
        </Modal>
      )}
    </div>
  );
}

// --- Shared styles ---
const inputCls = "w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3.5 py-2.5 text-sm text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:border-slate-400 dark:focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-400/20 transition-colors";

// --- Reusable components ---
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-full max-w-lg rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">{title}</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"><X className="h-5 w-5" /></button>
        </div>
        <div className="p-6 space-y-4">{children}</div>
      </div>
    </div>
  );
}

function ModalFooter({ t, saving, disabled, onCancel, onSave }: { t: (k: string) => string; saving: boolean; disabled: boolean; onCancel: () => void; onSave: () => void }) {
  return (
    <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800 mt-4">
      <button onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">{t("common.cancel")}</button>
      <button onClick={onSave} disabled={saving || disabled} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-5 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 disabled:opacity-50 transition-colors">
        {saving && <Loader2 className="h-4 w-4 animate-spin" />}
        {t("common.save")}
      </button>
    </div>
  );
}

function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}</label>
      {help && <p className="text-xs text-slate-400 dark:text-slate-500">{help}</p>}
      {children}
    </div>
  );
}

function countRules(folder: Folder): number {
  return folder.rules.length + folder.children.reduce((s, c) => s + countRules(c), 0);
}

// --- Folder node ---
function RuleFolderNode({ folder, depth, t, expanded, toggle, openCreateRule, openEditRule, toggleRule, openCreateFolder, openEditFolder, deleteConfirm, setDeleteConfirm, deleteRule, deleteFolder }: {
  folder: Folder; depth: number; t: (k: string) => string;
  expanded: Set<number>; toggle: (id: number) => void;
  openCreateRule: (folderId: number | null) => void;
  openEditRule: (rule: Rule) => void;
  toggleRule: (rule: Rule) => void;
  openCreateFolder: (parentId: number | null) => void;
  openEditFolder: (folder: Folder) => void;
  deleteConfirm: { type: string; id: number } | null;
  setDeleteConfirm: (v: { type: "rule" | "folder"; id: number } | null) => void;
  deleteRule: (id: number) => void;
  deleteFolder: (id: number) => void;
}) {
  const isExpanded = expanded.has(folder.id);
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-10" : depth === 2 ? "pl-16" : "pl-22";
  const folderColor = folder.type === "manufacturer" ? "text-amber-500" : folder.type === "model" ? "text-blue-500" : "text-slate-400 dark:text-slate-500";

  return (
    <>
      <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group`}>
        <button onClick={() => toggle(folder.id)} className="shrink-0">
          {isExpanded ? <ChevronDown className="h-4 w-4 text-slate-400" /> : <ChevronRight className="h-4 w-4 text-slate-400" />}
        </button>
        <button onClick={() => toggle(folder.id)} className="flex items-center gap-2 flex-1 min-w-0 text-left">
          {isExpanded ? <FolderOpen className={`h-5 w-5 ${folderColor} shrink-0`} /> : <FolderClosed className={`h-5 w-5 ${folderColor} shrink-0`} />}
          <span className="text-sm font-semibold text-slate-900 dark:text-slate-100 truncate">{folder.name}</span>
          {folder.autoGenerated && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium text-slate-500 bg-slate-100 ring-1 ring-inset ring-slate-200 dark:text-slate-400 dark:bg-slate-800 dark:ring-slate-700">auto</span>
          )}
          <span className="text-xs text-slate-400 dark:text-slate-500">{countRules(folder)} {t("collection_rules.rule")}{countRules(folder) !== 1 ? "s" : ""}</span>
        </button>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button onClick={() => openCreateRule(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("collection_rules.addRule")}>
            <Plus className="h-3.5 w-3.5" />
          </button>
          <button onClick={() => openCreateFolder(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("collection_rules.newFolder")}>
            <FolderPlus className="h-3.5 w-3.5" />
          </button>
          {!folder.autoGenerated && (
            <>
              <button onClick={() => openEditFolder(folder)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
                <Pencil className="h-3.5 w-3.5" />
              </button>
              {deleteConfirm?.type === "folder" && deleteConfirm.id === folder.id ? (
                <div className="flex items-center gap-1">
                  <button onClick={() => deleteFolder(folder.id)} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
                  <button onClick={() => setDeleteConfirm(null)} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
                </div>
              ) : (
                <button onClick={() => setDeleteConfirm({ type: "folder", id: folder.id })} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              )}
            </>
          )}
        </div>
      </div>

      {isExpanded && (
        <>
          {folder.children.map((child) => (
            <RuleFolderNode key={`folder-${child.id}`} folder={child} depth={depth + 1} t={t}
              expanded={expanded} toggle={toggle}
              openCreateRule={openCreateRule} openEditRule={openEditRule} toggleRule={toggleRule}
              openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
              deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
              deleteRule={deleteRule} deleteFolder={deleteFolder}
            />
          ))}
          {folder.rules.map((rule) => (
            <RuleRow key={`rule-${rule.id}`} rule={rule} depth={depth + 1} t={t}
              onEdit={() => openEditRule(rule)} onToggle={() => toggleRule(rule)}
              deleteConfirm={deleteConfirm?.type === "rule" && deleteConfirm.id === rule.id}
              onDelete={() => setDeleteConfirm({ type: "rule", id: rule.id })}
              onDeleteConfirm={() => deleteRule(rule.id)}
              onDeleteCancel={() => setDeleteConfirm(null)}
            />
          ))}
        </>
      )}
    </>
  );
}

// --- Rule row ---
function RuleRow({ rule, depth, t, onEdit, onToggle, deleteConfirm, onDelete, onDeleteConfirm, onDeleteCancel }: {
  rule: Rule; depth: number; t: (k: string) => string;
  onEdit: () => void; onToggle: () => void;
  deleteConfirm: boolean; onDelete: () => void; onDeleteConfirm: () => void; onDeleteCancel: () => void;
}) {
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-14" : depth === 2 ? "pl-20" : "pl-26";

  return (
    <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors group`}>
      <FileText className={`h-4 w-4 shrink-0 ${rule.enabled ? "text-emerald-500" : "text-slate-300 dark:text-slate-600"}`} />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <Link href={`/collection-rules/${rule.id}`} className={`text-sm font-medium hover:underline ${rule.enabled ? "text-slate-900 dark:text-slate-100" : "text-slate-400 dark:text-slate-500 line-through"}`}>{rule.name}</Link>
          {rule.source === "local" ? (
            <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium text-blue-700 bg-blue-50 ring-1 ring-inset ring-blue-600/20 dark:text-blue-400 dark:bg-blue-500/10 dark:ring-blue-500/20">
              <Monitor className="h-3 w-3" />
              {t("collection_rules.sourceLocal")}
            </span>
          ) : (
            <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium text-amber-700 bg-amber-50 ring-1 ring-inset ring-amber-600/20 dark:text-amber-400 dark:bg-amber-500/10 dark:ring-amber-500/20">
              <Wifi className="h-3 w-3" />
              {t("collection_rules.sourceSSH")}
            </span>
          )}
          <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium text-purple-700 bg-purple-50 ring-1 ring-inset ring-purple-600/20 dark:text-purple-400 dark:bg-purple-500/10 dark:ring-purple-500/20">
            {rule.extracts.length} regex
          </span>
          {rule.command && (
            <code className="text-xs text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 rounded px-2 py-0.5 max-w-xs truncate">
              {rule.command}
            </code>
          )}
          {!rule.enabled && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium text-slate-500 bg-slate-100 ring-1 ring-inset ring-slate-200 dark:text-slate-400 dark:bg-slate-800 dark:ring-slate-700">{t("collection_rules.disabled")}</span>
          )}
        </div>
        {rule.description && <p className="text-xs text-slate-400 dark:text-slate-500 truncate">{rule.description}</p>}
      </div>
      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button onClick={onToggle} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          {rule.enabled ? <ToggleRight className="h-4 w-4 text-emerald-500" /> : <ToggleLeft className="h-4 w-4" />}
        </button>
        <button onClick={onEdit} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          <Pencil className="h-3.5 w-3.5" />
        </button>
        {deleteConfirm ? (
          <div className="flex items-center gap-1">
            <button onClick={onDeleteConfirm} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
            <button onClick={onDeleteCancel} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
          </div>
        ) : (
          <button onClick={onDelete} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
    </div>
  );
}
