"use client";

import { useState, useEffect, useCallback } from "react";
import { useI18n } from "@/components/I18nProvider";
import { useAppContext } from "@/components/ContextProvider";
import {
  Loader2,
  Terminal,
  FolderOpen,
  FolderClosed,
  FolderPlus,
  FileText,
  Plus,
  Pencil,
  Trash2,
  X,
  ChevronRight,
  ChevronDown,
  ToggleLeft,
  ToggleRight,
} from "lucide-react";

interface Command {
  id: number;
  name: string;
  description: string | null;
  commands: string;
  enabled: boolean;
  folderId: number | null;
  createdAt: string;
}

interface Folder {
  id: number;
  name: string;
  type: "custom" | "manufacturer" | "model";
  parentId: number | null;
  autoGenerated: boolean;
  children: Folder[];
  commands: Command[];
}

interface TreeData {
  folders: Folder[];
  rootCommands: Command[];
}

export default function CollectionCommandsPage() {
  const { t } = useI18n();
  const { current } = useAppContext();
  const [tree, setTree] = useState<TreeData>({ folders: [], rootCommands: [] });
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  // Command modal
  const [cmdModal, setCmdModal] = useState(false);
  const [editingCmd, setEditingCmd] = useState<Command | null>(null);
  const [cmdFolderId, setCmdFolderId] = useState<number | null>(null);
  const [cmdName, setCmdName] = useState("");
  const [cmdDesc, setCmdDesc] = useState("");
  const [cmdCommands, setCmdCommands] = useState("");
  const [cmdEnabled, setCmdEnabled] = useState(true);
  const [saving, setSaving] = useState(false);

  // Folder modal
  const [folderModal, setFolderModal] = useState(false);
  const [editingFolder, setEditingFolder] = useState<Folder | null>(null);
  const [folderParentId, setFolderParentId] = useState<number | null>(null);
  const [folderName, setFolderName] = useState("");

  // Delete confirm
  const [deleteConfirm, setDeleteConfirm] = useState<{ type: "cmd" | "folder"; id: number } | null>(null);

  const load = useCallback(async () => {
    if (!current) return;
    const res = await fetch(`/api/collection-commands/tree?context=${current.id}`);
    if (res.ok) setTree(await res.json());
    setLoading(false);
  }, [current]);

  useEffect(() => { load(); }, [load]);

  const toggle = (id: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  // Command CRUD
  const openCreateCmd = (folderId: number | null) => {
    setEditingCmd(null);
    setCmdFolderId(folderId);
    setCmdName("");
    setCmdDesc("");
    setCmdCommands("");
    setCmdEnabled(true);
    setCmdModal(true);
  };

  const openEditCmd = (cmd: Command) => {
    setEditingCmd(cmd);
    setCmdFolderId(cmd.folderId);
    setCmdName(cmd.name);
    setCmdDesc(cmd.description ?? "");
    setCmdCommands(cmd.commands);
    setCmdEnabled(cmd.enabled);
    setCmdModal(true);
  };

  const saveCmd = async () => {
    if (!cmdName.trim() || !cmdCommands.trim()) return;
    setSaving(true);
    try {
      const body = { name: cmdName, description: cmdDesc || null, commands: cmdCommands, enabled: cmdEnabled, folderId: cmdFolderId };
      if (editingCmd) {
        await fetch(`/api/collection-commands/${editingCmd.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      } else {
        await fetch(`/api/collection-commands?context=${current!.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      }
      setCmdModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const toggleCmd = async (cmd: Command) => {
    await fetch(`/api/collection-commands/${cmd.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !cmd.enabled }) });
    await load();
  };

  const deleteCmd = async (id: number) => {
    await fetch(`/api/collection-commands/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  // Folder CRUD
  const openCreateFolder = (parentId: number | null) => {
    setEditingFolder(null);
    setFolderParentId(parentId);
    setFolderName("");
    setFolderModal(true);
  };

  const openEditFolder = (folder: Folder) => {
    setEditingFolder(folder);
    setFolderParentId(folder.parentId);
    setFolderName(folder.name);
    setFolderModal(true);
  };

  const saveFolder = async () => {
    if (!folderName.trim()) return;
    setSaving(true);
    try {
      if (editingFolder) {
        await fetch(`/api/collection-folders/${editingFolder.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName }) });
      } else {
        await fetch(`/api/collection-folders?context=${current!.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName, parentId: folderParentId }) });
      }
      setFolderModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const deleteFolder = async (id: number) => {
    await fetch(`/api/collection-folders/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  if (loading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-slate-900 dark:text-white" /></div>;
  }

  const isEmpty = tree.folders.length === 0 && tree.rootCommands.length === 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">{t("collection_commands.title")}</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{t("collection_commands.subtitle")}</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => openCreateFolder(null)} className="flex items-center gap-2 rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
            <FolderPlus className="h-4 w-4" />
            {t("collection_commands.newFolder")}
          </button>
          <button onClick={() => openCreateCmd(null)} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-4 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 transition-colors">
            <Plus className="h-4 w-4" />
            {t("collection_commands.newCommand")}
          </button>
        </div>
      </div>

      {isEmpty ? (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-12 text-center shadow-sm">
          <Terminal className="mx-auto h-8 w-8 text-slate-300 dark:text-slate-600 mb-2" />
          <p className="text-sm text-slate-400 dark:text-slate-500">{t("collection_commands.noCommands")}</p>
        </div>
      ) : (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm overflow-hidden">
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {/* Folders first */}
            {tree.folders.map((folder) => (
              <FolderNode key={`folder-${folder.id}`} folder={folder} depth={0} t={t}
                expanded={expanded} toggle={toggle}
                openCreateCmd={openCreateCmd} openEditCmd={openEditCmd} toggleCmd={toggleCmd}
                openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
                deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
                deleteCmd={deleteCmd} deleteFolder={deleteFolder}
              />
            ))}
            {/* Root commands after */}
            {tree.rootCommands.map((cmd) => (
              <CmdRow key={`cmd-${cmd.id}`} cmd={cmd} depth={0} t={t}
                onEdit={() => openEditCmd(cmd)} onToggle={() => toggleCmd(cmd)}
                deleteConfirm={deleteConfirm?.type === "cmd" && deleteConfirm.id === cmd.id}
                onDelete={() => setDeleteConfirm({ type: "cmd", id: cmd.id })}
                onDeleteConfirm={() => deleteCmd(cmd.id)}
                onDeleteCancel={() => setDeleteConfirm(null)}
              />
            ))}
          </div>
        </div>
      )}

      {/* Command Modal */}
      {cmdModal && (
        <Modal title={editingCmd ? t("collection_commands.editCommand") : t("collection_commands.newCommand")} onClose={() => setCmdModal(false)}>
          <div className="space-y-4">
            <Field label={t("collection_commands.name")}>
              <input type="text" value={cmdName} onChange={(e) => setCmdName(e.target.value)} placeholder={t("collection_commands.namePlaceholder")} className={inputCls} />
            </Field>
            <Field label={t("collection_commands.description")}>
              <input type="text" value={cmdDesc} onChange={(e) => setCmdDesc(e.target.value)} placeholder={t("collection_commands.descriptionPlaceholder")} className={inputCls} />
            </Field>
            <Field label={t("collection_commands.commandsLabel")} help={t("collection_commands.commandsHelp")}>
              <textarea value={cmdCommands} onChange={(e) => setCmdCommands(e.target.value)} rows={5} placeholder={t("collection_commands.commandsPlaceholder")} className={`${inputCls} font-mono resize-none`} />
            </Field>
            <label className="flex items-center gap-3 cursor-pointer">
              <button type="button" onClick={() => setCmdEnabled(!cmdEnabled)}>
                {cmdEnabled ? <ToggleRight className="h-6 w-6 text-emerald-500" /> : <ToggleLeft className="h-6 w-6 text-slate-400" />}
              </button>
              <span className="text-sm text-slate-700 dark:text-slate-300">{t("collection_commands.enabled")}</span>
            </label>
          </div>
          <ModalFooter t={t} saving={saving} disabled={!cmdName.trim() || !cmdCommands.trim()} onCancel={() => setCmdModal(false)} onSave={saveCmd} />
        </Modal>
      )}

      {/* Folder Modal */}
      {folderModal && (
        <Modal title={editingFolder ? t("collection_commands.editFolder") : t("collection_commands.newFolder")} onClose={() => setFolderModal(false)}>
          <Field label={t("collection_commands.folderName")}>
            <input type="text" value={folderName} onChange={(e) => setFolderName(e.target.value)} placeholder={t("collection_commands.folderNamePlaceholder")} className={inputCls} />
          </Field>
          <ModalFooter t={t} saving={saving} disabled={!folderName.trim()} onCancel={() => setFolderModal(false)} onSave={saveFolder} />
        </Modal>
      )}
    </div>
  );
}

// --- Shared styles ---
const inputCls = "w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3.5 py-2.5 text-sm text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:border-slate-400 dark:focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-400/20 transition-colors";

// --- Reusable components ---
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-full max-w-lg rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">{title}</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"><X className="h-5 w-5" /></button>
        </div>
        <div className="p-6 space-y-4">{children}</div>
      </div>
    </div>
  );
}

function ModalFooter({ t, saving, disabled, onCancel, onSave }: { t: (k: string) => string; saving: boolean; disabled: boolean; onCancel: () => void; onSave: () => void }) {
  return (
    <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800 mt-4">
      <button onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">{t("common.cancel")}</button>
      <button onClick={onSave} disabled={saving || disabled} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-5 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 disabled:opacity-50 transition-colors">
        {saving && <Loader2 className="h-4 w-4 animate-spin" />}
        {t("common.save")}
      </button>
    </div>
  );
}

function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}</label>
      {help && <p className="text-xs text-slate-400 dark:text-slate-500">{help}</p>}
      {children}
    </div>
  );
}

// --- Folder node ---
function FolderNode({ folder, depth, t, expanded, toggle, openCreateCmd, openEditCmd, toggleCmd, openCreateFolder, openEditFolder, deleteConfirm, setDeleteConfirm, deleteCmd, deleteFolder }: {
  folder: Folder; depth: number; t: (k: string) => string;
  expanded: Set<number>; toggle: (id: number) => void;
  openCreateCmd: (folderId: number | null) => void;
  openEditCmd: (cmd: Command) => void;
  toggleCmd: (cmd: Command) => void;
  openCreateFolder: (parentId: number | null) => void;
  openEditFolder: (folder: Folder) => void;
  deleteConfirm: { type: string; id: number } | null;
  setDeleteConfirm: (v: { type: "cmd" | "folder"; id: number } | null) => void;
  deleteCmd: (id: number) => void;
  deleteFolder: (id: number) => void;
}) {
  const isExpanded = expanded.has(folder.id);
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-10" : depth === 2 ? "pl-16" : "pl-22";
  const folderColor = folder.type === "manufacturer" ? "text-amber-500" : folder.type === "model" ? "text-blue-500" : "text-slate-400 dark:text-slate-500";
  const totalItems = folder.commands.length + folder.children.reduce((s, c) => s + c.commands.length + c.children.length, 0) + folder.children.length;

  return (
    <>
      <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group`}>
        <button onClick={() => toggle(folder.id)} className="shrink-0">
          {isExpanded ? <ChevronDown className="h-4 w-4 text-slate-400" /> : <ChevronRight className="h-4 w-4 text-slate-400" />}
        </button>
        <button onClick={() => toggle(folder.id)} className="flex items-center gap-2 flex-1 min-w-0 text-left">
          {isExpanded ? <FolderOpen className={`h-5 w-5 ${folderColor} shrink-0`} /> : <FolderClosed className={`h-5 w-5 ${folderColor} shrink-0`} />}
          <span className="text-sm font-semibold text-slate-900 dark:text-slate-100 truncate">{folder.name}</span>
          {folder.autoGenerated && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium text-slate-500 bg-slate-100 ring-1 ring-inset ring-slate-200 dark:text-slate-400 dark:bg-slate-800 dark:ring-slate-700">auto</span>
          )}
          <span className="text-xs text-slate-400 dark:text-slate-500">{folder.commands.length} cmd{folder.commands.length !== 1 ? "s" : ""}</span>
        </button>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button onClick={() => openCreateCmd(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("collection_commands.addCommand")}>
            <Plus className="h-3.5 w-3.5" />
          </button>
          <button onClick={() => openCreateFolder(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("collection_commands.newFolder")}>
            <FolderPlus className="h-3.5 w-3.5" />
          </button>
          {!folder.autoGenerated && (
            <>
              <button onClick={() => openEditFolder(folder)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
                <Pencil className="h-3.5 w-3.5" />
              </button>
              {deleteConfirm?.type === "folder" && deleteConfirm.id === folder.id ? (
                <div className="flex items-center gap-1">
                  <button onClick={() => deleteFolder(folder.id)} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
                  <button onClick={() => setDeleteConfirm(null)} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
                </div>
              ) : (
                <button onClick={() => setDeleteConfirm({ type: "folder", id: folder.id })} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              )}
            </>
          )}
        </div>
      </div>

      {isExpanded && (
        <>
          {folder.children.map((child) => (
            <FolderNode key={`folder-${child.id}`} folder={child} depth={depth + 1} t={t}
              expanded={expanded} toggle={toggle}
              openCreateCmd={openCreateCmd} openEditCmd={openEditCmd} toggleCmd={toggleCmd}
              openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
              deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
              deleteCmd={deleteCmd} deleteFolder={deleteFolder}
            />
          ))}
          {folder.commands.map((cmd) => (
            <CmdRow key={`cmd-${cmd.id}`} cmd={cmd} depth={depth + 1} t={t}
              onEdit={() => openEditCmd(cmd)} onToggle={() => toggleCmd(cmd)}
              deleteConfirm={deleteConfirm?.type === "cmd" && deleteConfirm.id === cmd.id}
              onDelete={() => setDeleteConfirm({ type: "cmd", id: cmd.id })}
              onDeleteConfirm={() => deleteCmd(cmd.id)}
              onDeleteCancel={() => setDeleteConfirm(null)}
            />
          ))}
        </>
      )}
    </>
  );
}

// --- Command row ---
function CmdRow({ cmd, depth, t, onEdit, onToggle, deleteConfirm, onDelete, onDeleteConfirm, onDeleteCancel }: {
  cmd: Command; depth: number; t: (k: string) => string;
  onEdit: () => void; onToggle: () => void;
  deleteConfirm: boolean; onDelete: () => void; onDeleteConfirm: () => void; onDeleteCancel: () => void;
}) {
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-14" : depth === 2 ? "pl-20" : "pl-26";

  return (
    <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors group`}>
      <FileText className={`h-4 w-4 shrink-0 ${cmd.enabled ? "text-emerald-500" : "text-slate-300 dark:text-slate-600"}`} />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span className={`text-sm font-medium ${cmd.enabled ? "text-slate-900 dark:text-slate-100" : "text-slate-400 dark:text-slate-500 line-through"}`}>{cmd.name}</span>
          {!cmd.enabled && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium text-slate-500 bg-slate-100 ring-1 ring-inset ring-slate-200 dark:text-slate-400 dark:bg-slate-800 dark:ring-slate-700">{t("collection_commands.disabled")}</span>
          )}
        </div>
        {cmd.description && <p className="text-xs text-slate-400 dark:text-slate-500 truncate">{cmd.description}</p>}
      </div>
      <code className="hidden sm:block text-xs text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 rounded px-2 py-1 max-w-xs truncate">
        {cmd.commands.split("\n")[0]}{cmd.commands.includes("\n") ? "..." : ""}
      </code>
      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button onClick={onToggle} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          {cmd.enabled ? <ToggleRight className="h-4 w-4 text-emerald-500" /> : <ToggleLeft className="h-4 w-4" />}
        </button>
        <button onClick={onEdit} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          <Pencil className="h-3.5 w-3.5" />
        </button>
        {deleteConfirm ? (
          <div className="flex items-center gap-1">
            <button onClick={onDeleteConfirm} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
            <button onClick={onDeleteCancel} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
          </div>
        ) : (
          <button onClick={onDelete} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
    </div>
  );
}
