<?php

namespace App\Entity;

use App\Repository\CollectionFolderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CollectionFolderRepository::class)]
class CollectionFolder
{
    public const TYPE_CUSTOM = 'custom';
    public const TYPE_MANUFACTURER = 'manufacturer';
    public const TYPE_MODEL = 'model';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private string $name;

    #[ORM\Column(length: 20)]
    private string $type = self::TYPE_CUSTOM;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    private ?self $parent = null;

    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'parent')]
    #[ORM\OrderBy(['name' => 'ASC'])]
    private Collection $children;

    #[ORM\ManyToOne(targetEntity: Editor::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    private ?Editor $manufacturer = null;

    #[ORM\ManyToOne(targetEntity: DeviceModel::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    private ?DeviceModel $model = null;

    #[ORM\ManyToOne(targetEntity: Context::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Context $context;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->children = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int { return $this->id; }
    public function getName(): string { return $this->name; }
    public function setName(string $v): static { $this->name = $v; return $this; }
    public function getType(): string { return $this->type; }
    public function setType(string $v): static { $this->type = $v; return $this; }
    public function getParent(): ?self { return $this->parent; }
    public function setParent(?self $v): static { $this->parent = $v; return $this; }
    /** @return Collection<int, self> */
    public function getChildren(): Collection { return $this->children; }
    public function getManufacturer(): ?Editor { return $this->manufacturer; }
    public function setManufacturer(?Editor $v): static { $this->manufacturer = $v; return $this; }
    public function getModel(): ?DeviceModel { return $this->model; }
    public function setModel(?DeviceModel $v): static { $this->model = $v; return $this; }
    public function getContext(): Context { return $this->context; }
    public function setContext(Context $v): static { $this->context = $v; return $this; }
    public function getCreatedAt(): \DateTimeImmutable { return $this->createdAt; }
    public function isAutoGenerated(): bool { return $this->type !== self::TYPE_CUSTOM; }
}
