<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'topology_edge')]
#[ORM\Index(columns: ['topology_id'], name: 'idx_topology_edge_topology')]
#[ORM\Index(columns: ['source_node_id'], name: 'idx_topology_edge_source')]
#[ORM\Index(columns: ['target_node_id'], name: 'idx_topology_edge_target')]
class TopologyEdge
{
    public const TYPE_STRAIGHT = 'straight';
    public const TYPE_ORTHOGONAL = 'orthogonal';
    public const TYPE_CURVED = 'curved';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Topology::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Topology $topology;

    #[ORM\ManyToOne(targetEntity: Node::class)]
    #[ORM\JoinColumn(name: 'source_node_id', nullable: false, onDelete: 'CASCADE')]
    private Node $sourceNode;

    #[ORM\ManyToOne(targetEntity: Node::class)]
    #[ORM\JoinColumn(name: 'target_node_id', nullable: false, onDelete: 'CASCADE')]
    private Node $targetNode;

    /**
     * Visual style: {
     *   type: "straight"|"orthogonal"|"curved",
     *   color: "#94a3b8",
     *   width: 1.5,
     *   dash: "solid"|"dashed"|"dotted",
     *   curveTension: number (curved only, 0..1),
     *   labels: [{ text, position: "source"|"middle"|"target", offset, fontSize, color, fontWeight, background }]
     * }
     */
    #[ORM\Column(type: 'json')]
    private array $style = [];

    /**
     * If set, this edge was generated by a TopologyProtocol (it is overwritten when the protocol
     * is regenerated). Null = manual edge (preserved across regenerations).
     */
    #[ORM\ManyToOne(targetEntity: TopologyProtocol::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?TopologyProtocol $protocol = null;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int { return $this->id; }
    public function getTopology(): Topology { return $this->topology; }
    public function setTopology(Topology $v): static { $this->topology = $v; return $this; }
    public function getSourceNode(): Node { return $this->sourceNode; }
    public function setSourceNode(Node $v): static { $this->sourceNode = $v; return $this; }
    public function getTargetNode(): Node { return $this->targetNode; }
    public function setTargetNode(Node $v): static { $this->targetNode = $v; return $this; }
    public function getStyle(): array { return $this->style; }
    public function setStyle(array $v): static { $this->style = $v; return $this; }
    public function getProtocol(): ?TopologyProtocol { return $this->protocol; }
    public function setProtocol(?TopologyProtocol $v): static { $this->protocol = $v; return $this; }
    public function getCreatedAt(): \DateTimeImmutable { return $this->createdAt; }

    public static function defaultStyle(): array
    {
        return [
            'type' => self::TYPE_STRAIGHT,
            'color' => '#94a3b8',
            'width' => 0.5,
            'dash' => 'solid',
            'curveTension' => 0.3,
            'labels' => [],
        ];
    }
}
