<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'topology_cluster')]
#[ORM\Index(columns: ['topology_id'], name: 'idx_topology_cluster_topology')]
class TopologyCluster
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Topology::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Topology $topology;

    #[ORM\Column(length: 255)]
    private string $name;

    /**
     * Visual style: {
     *   borderColor, borderWidth, dash: "solid"|"dashed"|"dotted",
     *   fillColor, transparent: bool,
     *   padding: number, borderRadius: number,
     *   labelPosition: "top"|"bottom"|"none", labelFontSize, labelColor
     * }
     */
    #[ORM\Column(type: 'json')]
    private array $style = [];

    /**
     * If set, this cluster was auto-generated by a TopologyProtocol (e.g. ISIS area).
     * It will be wiped and regenerated on every protocol run. Null = manual cluster.
     */
    #[ORM\ManyToOne(targetEntity: TopologyProtocol::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?TopologyProtocol $protocol = null;

    /**
     * If set, this cluster was auto-generated by a TopologyClusterRule grouping
     * nodes on an inventory column. Wiped and regenerated every rule run.
     */
    #[ORM\ManyToOne(targetEntity: TopologyClusterRule::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?TopologyClusterRule $clusterRule = null;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int { return $this->id; }
    public function getTopology(): Topology { return $this->topology; }
    public function setTopology(Topology $v): static { $this->topology = $v; return $this; }
    public function getName(): string { return $this->name; }
    public function setName(string $v): static { $this->name = $v; return $this; }
    public function getStyle(): array { return $this->style; }
    public function setStyle(array $v): static { $this->style = $v; return $this; }
    public function getProtocol(): ?TopologyProtocol { return $this->protocol; }
    public function setProtocol(?TopologyProtocol $v): static { $this->protocol = $v; return $this; }
    public function getClusterRule(): ?TopologyClusterRule { return $this->clusterRule; }
    public function setClusterRule(?TopologyClusterRule $v): static { $this->clusterRule = $v; return $this; }
    public function getCreatedAt(): \DateTimeImmutable { return $this->createdAt; }

    public static function defaultStyle(): array
    {
        return [
            'borderColor' => '#ef4444',
            'borderWidth' => 0.5,
            'dash' => 'dashed',
            'fillColor' => '#ef4444',
            'transparent' => true,
            'padding' => 5,
            'borderRadius' => 12,
            'labelPosition' => 'none',
            'labelFontSize' => 6,
            'labelColor' => '#ef4444',
        ];
    }
}
