nelmio_api_doc:
    documentation:
        info:
            title: Auditix Public API
            description: REST API for managing nodes, triggering collections, and checking compliance.
            version: '1.0.0'
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: "API Token"
        security:
            - BearerAuth: []
    areas:
        default:
            path_patterns:
                - ^/api/v1/
