"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useI18n } from "@/components/I18nProvider";
import { useAppContext } from "@/components/ContextProvider";
import {
  Loader2,
  ClipboardCheck,
  FolderOpen,
  FolderClosed,
  FolderPlus,
  FileText,
  Plus,
  Pencil,
  Trash2,
  X,
  ChevronRight,
  ChevronDown,
  ToggleLeft,
  ToggleRight,
  BookOpen,
  Download,
  Upload,
  CheckCircle2,
  Tag,
} from "lucide-react";

interface Rule {
  id: number;
  identifier: string | null;
  name: string;
  description: string | null;
  enabled: boolean;
  folderId: number | null;
  createdAt: string;
}

interface Folder {
  id: number;
  name: string;
  parentId: number | null;
  policyId: number | null;
  autoGenerated: boolean;
  children: Folder[];
  rules: Rule[];
}

interface TreeData {
  folders: Folder[];
  rootRules: Rule[];
}

export default function ComplianceRulesPage() {
  const { t } = useI18n();
  const { current } = useAppContext();
  const router = useRouter();
  const [tree, setTree] = useState<TreeData>({ folders: [], rootRules: [] });
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  // Rule modal
  const [ruleModal, setRuleModal] = useState(false);
  const [ruleFolderId, setRuleFolderId] = useState<number | null>(null);
  const [ruleIdentifier, setRuleIdentifier] = useState("");
  const [ruleName, setRuleName] = useState("");
  const [ruleDesc, setRuleDesc] = useState("");
  const [ruleEnabled, setRuleEnabled] = useState(true);
  const [saving, setSaving] = useState(false);

  // Folder modal
  const [folderModal, setFolderModal] = useState(false);
  const [editingFolder, setEditingFolder] = useState<Folder | null>(null);
  const [folderParentId, setFolderParentId] = useState<number | null>(null);
  const [folderName, setFolderName] = useState("");

  // Delete confirm
  const [deleteConfirm, setDeleteConfirm] = useState<{ type: "rule" | "folder"; id: number } | null>(null);

  // Export/Import
  const [exportingId, setExportingId] = useState<number | null>(null);
  const [importTargetId, setImportTargetId] = useState<number | null>(null);
  const [importPreview, setImportPreview] = useState<{ folderName: string; ruleCount: number; subfolderCount: number; categories: { name: string; exists: boolean }[] } | null>(null);
  const [importFile, setImportFile] = useState<File | null>(null);
  const [importLoading, setImportLoading] = useState(false);
  const importInputRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => {
    if (!current) return;
    const res = await fetch(`/api/compliance-rules/tree?context=${current.id}`);
    if (res.ok) setTree(await res.json());
    setLoading(false);
  }, [current]);

  useEffect(() => { load(); }, [load]);

  const toggle = (id: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  // Rule CRUD
  const openCreateRule = (folderId: number | null) => {
    setRuleFolderId(folderId);
    setRuleIdentifier("");
    setRuleName("");
    setRuleDesc("");
    setRuleEnabled(true);
    setRuleModal(true);
  };

  const saveRule = async () => {
    if (!ruleName.trim()) return;
    setSaving(true);
    try {
      await fetch(`/api/compliance-rules?context=${current!.id}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ identifier: ruleIdentifier || null, name: ruleName, description: ruleDesc || null, enabled: ruleEnabled, folderId: ruleFolderId }),
      });
      setRuleModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const toggleRule = async (rule: Rule) => {
    await fetch(`/api/compliance-rules/${rule.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !rule.enabled }) });
    await load();
  };

  const deleteRule = async (id: number) => {
    await fetch(`/api/compliance-rules/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  // Folder CRUD
  const openCreateFolder = (parentId: number | null) => {
    setEditingFolder(null);
    setFolderParentId(parentId);
    setFolderName("");
    setFolderModal(true);
  };

  const openEditFolder = (folder: Folder) => {
    setEditingFolder(folder);
    setFolderParentId(folder.parentId);
    setFolderName(folder.name);
    setFolderModal(true);
  };

  const saveFolder = async () => {
    if (!folderName.trim()) return;
    setSaving(true);
    try {
      if (editingFolder) {
        await fetch(`/api/compliance-rule-folders/${editingFolder.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName }) });
      } else {
        await fetch(`/api/compliance-rule-folders?context=${current!.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: folderName, parentId: folderParentId }) });
      }
      setFolderModal(false);
      await load();
    } finally { setSaving(false); }
  };

  const deleteFolder = async (id: number) => {
    await fetch(`/api/compliance-rule-folders/${id}`, { method: "DELETE" });
    setDeleteConfirm(null);
    await load();
  };

  const handleExportFolder = async (folderId: number, folderName: string) => {
    setExportingId(folderId);
    try {
      const res = await fetch(`/api/compliance-rule-folders/${folderId}/export`);
      if (!res.ok) throw new Error("Export failed");
      const blob = await res.blob();
      const disposition = res.headers.get("Content-Disposition") || "";
      const match = disposition.match(/filename="?([^"]+)"?/);
      const filename = match?.[1] || `compliance-rules-${folderName}.json`;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) { console.error(e); } finally { setExportingId(null); }
  };

  const handleImportFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !current) return;
    if (importInputRef.current) importInputRef.current.value = "";
    setImportFile(file);
    setImportLoading(true);
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch(`/api/compliance-rule-folders/preview-import?context=${current.id}`, { method: "POST", body: formData });
      if (!res.ok) { const err = await res.json(); throw new Error(err.error || "Preview failed"); }
      setImportPreview(await res.json());
    } catch (e: unknown) {
      alert(e instanceof Error ? e.message : "Preview failed");
      setImportFile(null);
      setImportTargetId(null);
    } finally { setImportLoading(false); }
  };

  const handleConfirmImportFolder = async () => {
    if (!importFile || !current) return;
    setImportLoading(true);
    try {
      const formData = new FormData();
      formData.append("file", importFile);
      const parentParam = importTargetId ? `&parentId=${importTargetId}` : "";
      const res = await fetch(`/api/compliance-rule-folders/import?context=${current.id}${parentParam}`, { method: "POST", body: formData });
      if (!res.ok) { const err = await res.json(); throw new Error(err.error || "Import failed"); }
      await load();
    } catch (e: unknown) { alert(e instanceof Error ? e.message : "Import failed"); }
    finally {
      setImportLoading(false);
      setImportFile(null);
      setImportPreview(null);
      setImportTargetId(null);
    }
  };

  const closeImportModal = () => { setImportFile(null); setImportPreview(null); setImportTargetId(null); };

  if (loading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-slate-900 dark:text-white" /></div>;
  }

  const isEmpty = tree.folders.length === 0 && tree.rootRules.length === 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">{t("compliance_rules.title")}</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{t("compliance_rules.subtitle")}</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => { setImportTargetId(null); importInputRef.current?.click(); }} className="flex items-center gap-2 rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
            <Upload className="h-4 w-4" />
            {t("compliance_rules.importFolder")}
          </button>
          <button onClick={() => openCreateFolder(null)} className="flex items-center gap-2 rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2.5 text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
            <FolderPlus className="h-4 w-4" />
            {t("compliance_rules.newFolder")}
          </button>
          <button onClick={() => openCreateRule(null)} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-4 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 transition-colors">
            <Plus className="h-4 w-4" />
            {t("compliance_rules.newRule")}
          </button>
        </div>
      </div>

      {isEmpty ? (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-12 text-center shadow-sm">
          <ClipboardCheck className="mx-auto h-8 w-8 text-slate-300 dark:text-slate-600 mb-2" />
          <p className="text-sm text-slate-400 dark:text-slate-500">{t("compliance_rules.noRules")}</p>
        </div>
      ) : (
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm overflow-hidden">
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {tree.folders.map((folder) => (
              <ComplianceFolderNode key={`folder-${folder.id}`} folder={folder} depth={0} t={t}
                expanded={expanded} toggle={toggle}
                openCreateRule={openCreateRule} toggleRule={toggleRule}
                openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
                deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
                deleteRule={deleteRule} deleteFolder={deleteFolder}
                exportingId={exportingId} onExport={handleExportFolder}
                onImport={(parentId) => { setImportTargetId(parentId); importInputRef.current?.click(); }}
              />
            ))}
            {tree.rootRules.map((rule) => (
              <ComplianceRuleRow key={`rule-${rule.id}`} rule={rule} depth={0} t={t}
                onToggle={() => toggleRule(rule)}
                deleteConfirm={deleteConfirm?.type === "rule" && deleteConfirm.id === rule.id}
                onDelete={() => setDeleteConfirm({ type: "rule", id: rule.id })}
                onDeleteConfirm={() => deleteRule(rule.id)}
                onDeleteCancel={() => setDeleteConfirm(null)}
              />
            ))}
          </div>
        </div>
      )}

      {/* Rule Modal */}
      {ruleModal && (
        <Modal title={t("compliance_rules.newRule")} onClose={() => setRuleModal(false)}>
          <div className="space-y-4">
            <Field label={t("compliance_rules.identifier")}>
              <input type="text" value={ruleIdentifier} onChange={(e) => setRuleIdentifier(e.target.value)} placeholder={t("compliance_rules.identifierPlaceholder")} className={`${inputCls} font-mono`} />
            </Field>
            <Field label={t("compliance_rules.name")}>
              <input type="text" value={ruleName} onChange={(e) => setRuleName(e.target.value)} placeholder={t("compliance_rules.namePlaceholder")} className={inputCls} />
            </Field>
            <Field label={t("compliance_rules.description")}>
              <input type="text" value={ruleDesc} onChange={(e) => setRuleDesc(e.target.value)} placeholder={t("compliance_rules.descriptionPlaceholder")} className={inputCls} />
            </Field>
            <label className="flex items-center gap-3 cursor-pointer">
              <button type="button" onClick={() => setRuleEnabled(!ruleEnabled)}>
                {ruleEnabled ? <ToggleRight className="h-6 w-6 text-emerald-500" /> : <ToggleLeft className="h-6 w-6 text-slate-400" />}
              </button>
              <span className="text-sm text-slate-700 dark:text-slate-300">{t("compliance_rules.enabled")}</span>
            </label>
          </div>
          <ModalFooter t={t} saving={saving} disabled={!ruleName.trim()} onCancel={() => setRuleModal(false)} onSave={saveRule} />
        </Modal>
      )}

      {/* Folder Modal */}
      {folderModal && (
        <Modal title={editingFolder ? t("compliance_rules.editFolder") : t("compliance_rules.newFolder")} onClose={() => setFolderModal(false)}>
          <Field label={t("compliance_rules.folderName")}>
            <input type="text" value={folderName} onChange={(e) => setFolderName(e.target.value)} placeholder={t("compliance_rules.folderNamePlaceholder")} className={inputCls} />
          </Field>
          <ModalFooter t={t} saving={saving} disabled={!folderName.trim()} onCancel={() => setFolderModal(false)} onSave={saveFolder} />
        </Modal>
      )}

      {/* Hidden file input for import */}
      <input ref={importInputRef} type="file" accept=".json" onChange={handleImportFileSelect} className="hidden" />

      {/* Import preview modal */}
      {importFile && (importPreview || importLoading) && (
        <Modal title={t("compliance_rules.importPreviewTitle")} onClose={closeImportModal}>
          {importLoading && !importPreview ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin text-slate-900 dark:text-white" />
            </div>
          ) : importPreview && (
            <>
              <div className="space-y-3">
                <div className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-3">
                  <p className="text-sm font-medium text-slate-900 dark:text-slate-100">{importPreview.folderName}</p>
                  <div className="flex items-center gap-4 mt-2 text-xs text-slate-500 dark:text-slate-400">
                    <span>{importPreview.ruleCount} {t("compliance_rules.importCountRules")}</span>
                    {importPreview.subfolderCount > 0 && <span>{importPreview.subfolderCount} {t("compliance_rules.importCountFolders")}</span>}
                  </div>
                </div>
                {importPreview.categories.length > 0 && (
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                      <Tag className="h-3.5 w-3.5" />
                      {t("compliance_rules.importSectionCategories")} ({importPreview.categories.length})
                    </div>
                    <div className="rounded-lg border border-slate-200 dark:border-slate-700 divide-y divide-slate-100 dark:divide-slate-800">
                      {importPreview.categories.map((c, i) => (
                        <div key={i} className="px-4 py-2.5 flex items-center justify-between">
                          <span className="text-sm text-slate-700 dark:text-slate-300">{c.name}</span>
                          {c.exists ? (
                            <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium bg-slate-100 text-slate-600 ring-1 ring-inset ring-slate-300/50 dark:bg-slate-800 dark:text-slate-400 dark:ring-slate-600/50">
                              <CheckCircle2 className="h-3 w-3" />
                              {t("compliance_rules.importExists")}
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-600/20 dark:bg-emerald-500/10 dark:text-emerald-400 dark:ring-emerald-500/20">
                              <Plus className="h-3 w-3" />
                              {t("compliance_rules.importNew")}
                            </span>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
              <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800 mt-4">
                <button onClick={closeImportModal} className="rounded-lg px-4 py-2.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">{t("common.cancel")}</button>
                <button onClick={handleConfirmImportFolder} disabled={importLoading} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-5 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 disabled:opacity-50 transition-colors">
                  {importLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
                  {t("compliance_rules.importConfirm")}
                </button>
              </div>
            </>
          )}
        </Modal>
      )}
    </div>
  );
}

// --- Shared styles ---
const inputCls = "w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3.5 py-2.5 text-sm text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:border-slate-400 dark:focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-400/20 transition-colors";

// --- Reusable components ---
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-full max-w-lg rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">{title}</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"><X className="h-5 w-5" /></button>
        </div>
        <div className="p-6 space-y-4">{children}</div>
      </div>
    </div>
  );
}

function ModalFooter({ t, saving, disabled, onCancel, onSave }: { t: (k: string) => string; saving: boolean; disabled: boolean; onCancel: () => void; onSave: () => void }) {
  return (
    <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800 mt-4">
      <button onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">{t("common.cancel")}</button>
      <button onClick={onSave} disabled={saving || disabled} className="flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-white px-5 py-2.5 text-sm font-medium text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 disabled:opacity-50 transition-colors">
        {saving && <Loader2 className="h-4 w-4 animate-spin" />}
        {t("common.save")}
      </button>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}</label>
      {children}
    </div>
  );
}

function countRules(folder: Folder): number {
  return folder.rules.length + folder.children.reduce((s, c) => s + countRules(c), 0);
}

// --- Folder node ---
function ComplianceFolderNode({ folder, depth, t, expanded, toggle, openCreateRule, toggleRule, openCreateFolder, openEditFolder, deleteConfirm, setDeleteConfirm, deleteRule, deleteFolder, exportingId, onExport, onImport }: {
  folder: Folder; depth: number; t: (k: string) => string;
  expanded: Set<number>; toggle: (id: number) => void;
  openCreateRule: (folderId: number | null) => void;
  toggleRule: (rule: Rule) => void;
  openCreateFolder: (parentId: number | null) => void;
  openEditFolder: (folder: Folder) => void;
  deleteConfirm: { type: string; id: number } | null;
  setDeleteConfirm: (v: { type: "rule" | "folder"; id: number } | null) => void;
  deleteRule: (id: number) => void;
  deleteFolder: (id: number) => void;
  exportingId: number | null;
  onExport: (id: number, name: string) => void;
  onImport: (parentId: number) => void;
}) {
  const isExpanded = expanded.has(folder.id);
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-10" : depth === 2 ? "pl-16" : "pl-22";
  const folderColor = folder.autoGenerated ? "text-blue-500" : "text-slate-400 dark:text-slate-500";

  return (
    <>
      <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group`}>
        <button onClick={() => toggle(folder.id)} className="shrink-0">
          {isExpanded ? <ChevronDown className="h-4 w-4 text-slate-400" /> : <ChevronRight className="h-4 w-4 text-slate-400" />}
        </button>
        <button onClick={() => toggle(folder.id)} className="flex items-center gap-2 flex-1 min-w-0 text-left">
          {isExpanded ? <FolderOpen className={`h-5 w-5 ${folderColor} shrink-0`} /> : <FolderClosed className={`h-5 w-5 ${folderColor} shrink-0`} />}
          <span className="text-sm font-semibold text-slate-900 dark:text-slate-100 truncate">{folder.name}</span>
          {folder.autoGenerated && (
            <BookOpen className="h-3.5 w-3.5 text-blue-400 shrink-0" />
          )}
          <span className="text-xs text-slate-400 dark:text-slate-500">{countRules(folder)} {t("compliance_rules.rule")}{countRules(folder) !== 1 ? "s" : ""}</span>
        </button>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button onClick={() => openCreateRule(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("compliance_rules.addRule")}>
            <Plus className="h-3.5 w-3.5" />
          </button>
          <button onClick={() => openCreateFolder(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors" title={t("compliance_rules.newFolder")}>
            <FolderPlus className="h-3.5 w-3.5" />
          </button>
          {!folder.autoGenerated && (
            <>
              <button onClick={() => onExport(folder.id, folder.name)} disabled={exportingId === folder.id} className="rounded-lg p-1.5 text-slate-400 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-500/10 transition-colors disabled:opacity-50" title={t("compliance_rules.exportFolder")}>
                {exportingId === folder.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
              </button>
              <button onClick={() => onImport(folder.id)} className="rounded-lg p-1.5 text-slate-400 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-500/10 transition-colors" title={t("compliance_rules.importFolder")}>
                <Upload className="h-3.5 w-3.5" />
              </button>
              <button onClick={() => openEditFolder(folder)} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
                <Pencil className="h-3.5 w-3.5" />
              </button>
              {deleteConfirm?.type === "folder" && deleteConfirm.id === folder.id ? (
                <div className="flex items-center gap-1">
                  <button onClick={() => deleteFolder(folder.id)} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
                  <button onClick={() => setDeleteConfirm(null)} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
                </div>
              ) : (
                <button onClick={() => setDeleteConfirm({ type: "folder", id: folder.id })} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              )}
            </>
          )}
        </div>
      </div>

      {isExpanded && (
        <>
          {folder.children.map((child) => (
            <ComplianceFolderNode key={`folder-${child.id}`} folder={child} depth={depth + 1} t={t}
              expanded={expanded} toggle={toggle}
              openCreateRule={openCreateRule} toggleRule={toggleRule}
              openCreateFolder={openCreateFolder} openEditFolder={openEditFolder}
              deleteConfirm={deleteConfirm} setDeleteConfirm={setDeleteConfirm}
              deleteRule={deleteRule} deleteFolder={deleteFolder}
              exportingId={exportingId} onExport={onExport} onImport={onImport}
            />
          ))}
          {folder.rules.map((rule) => (
            <ComplianceRuleRow key={`rule-${rule.id}`} rule={rule} depth={depth + 1} t={t}
              onToggle={() => toggleRule(rule)}
              deleteConfirm={deleteConfirm?.type === "rule" && deleteConfirm.id === rule.id}
              onDelete={() => setDeleteConfirm({ type: "rule", id: rule.id })}
              onDeleteConfirm={() => deleteRule(rule.id)}
              onDeleteCancel={() => setDeleteConfirm(null)}
            />
          ))}
        </>
      )}
    </>
  );
}

// --- Rule row ---
function ComplianceRuleRow({ rule, depth, t, onToggle, deleteConfirm, onDelete, onDeleteConfirm, onDeleteCancel }: {
  rule: Rule; depth: number; t: (k: string) => string;
  onToggle: () => void;
  deleteConfirm: boolean; onDelete: () => void; onDeleteConfirm: () => void; onDeleteCancel: () => void;
}) {
  const pl = depth === 0 ? "pl-4" : depth === 1 ? "pl-14" : depth === 2 ? "pl-20" : "pl-26";

  return (
    <div className={`flex items-center gap-3 ${pl} pr-4 py-2.5 hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors group`}>
      <FileText className={`h-4 w-4 shrink-0 ${rule.enabled ? "text-emerald-500" : "text-slate-300 dark:text-slate-600"}`} />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          {rule.identifier && (
            <code className="text-xs text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 rounded px-2 py-0.5 font-mono">{rule.identifier}</code>
          )}
          <Link href={`/compliance/rules/${rule.id}`} className={`text-sm font-medium hover:underline ${rule.enabled ? "text-slate-900 dark:text-slate-100" : "text-slate-400 dark:text-slate-500 line-through"}`}>{rule.name}</Link>
          {!rule.enabled && (
            <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium text-slate-500 bg-slate-100 ring-1 ring-inset ring-slate-200 dark:text-slate-400 dark:bg-slate-800 dark:ring-slate-700">{t("compliance_rules.disabled")}</span>
          )}
        </div>
        {rule.description && <p className="text-xs text-slate-400 dark:text-slate-500 truncate">{rule.description}</p>}
      </div>
      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button onClick={onToggle} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          {rule.enabled ? <ToggleRight className="h-4 w-4 text-emerald-500" /> : <ToggleLeft className="h-4 w-4" />}
        </button>
        <Link href={`/compliance/rules/${rule.id}`} className="rounded-lg p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-200/50 dark:hover:bg-slate-700/50 transition-colors">
          <Pencil className="h-3.5 w-3.5" />
        </Link>
        {deleteConfirm ? (
          <div className="flex items-center gap-1">
            <button onClick={onDeleteConfirm} className="rounded-lg px-2 py-1 text-xs font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-500/10">{t("common.delete")}</button>
            <button onClick={onDeleteCancel} className="rounded-lg px-2 py-1 text-xs font-medium text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{t("common.cancel")}</button>
          </div>
        ) : (
          <button onClick={onDelete} className="rounded-lg p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors">
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
    </div>
  );
}
